/*
 50recode v1.10.73
 FILE_CHANGED_ON = '2017-08-09 13:42:02'
 This source code is property of Intel Corporation.
 DO NOT duplicate, copy or modify this file or any subfiles referenced by this file.
 Please contact the IGHF team if you have issues.
*/
INTELNAV=window.INTELNAV||{};
function hf_debug(method,message,obj,debugLvl,isdebug){if(debugLvl<=isdebug&&typeof console!=="undefined"){function indent(counter){var indents="",i=0;for(i=0;i<counter;i++)indents=indents+"\t";return indents}var color=["#FF0000","#FFBF00","#80FF00","#00B359","#00BFFF","#265CFF","#5C26FF","#D24CFF"];var isdebug_indent="",isdebug_bundle_counter=0;switch(method){case "warn":isdebug_indent=indent(isdebug_bundle_counter);console.warn("%c50recode: "+isdebug_indent+message+obj,"background-color:#cc0000;color:#fff;");
break;case "info":isdebug_indent=indent(isdebug_bundle_counter);console.info("50recode: "+isdebug_indent+message+obj);break;case "error":isdebug_indent=indent(isdebug_bundle_counter);console.error("50recode: "+isdebug_indent+message+obj);break;case "properties":isdebug_indent=indent(isdebug_bundle_counter);console.dir("50recode: "+isdebug_indent+obj);break;case "timestamp":isdebug_indent=indent(isdebug_bundle_counter);if(/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor))console.timeStamp("50recode: "+
isdebug_indent+message);break;case "timestart":isdebug_indent=indent(isdebug_bundle_counter);if(/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor))console.time("50recode: "+isdebug_indent+message);break;case "timeend":isdebug_indent=indent(isdebug_bundle_counter);if(/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor))console.timeEnd("50recode: "+isdebug_indent+message);break;case "bundletimestart":if(/Safari/.test(navigator.userAgent)&&/Apple Computer/.test(navigator.vendor)){isdebug_indent=
indent(isdebug_bundle_counter);console.log("%c50recode: "+isdebug_indent+"START "+message+obj,"color:"+color[isdebug_bundle_counter]+";");console.timeStamp("50recode: "+isdebug_indent+"START "+message);console.time("50recode: "+isdebug_indent+message);isdebug_bundle_counter+=1;isdebug_indent=""}break;case "bundletimeend":if(/Safari/.test(navigator.userAgent)&&/Apple Computer/.test(navigator.vendor)){isdebug_bundle_counter-=1;isdebug_indent=indent(isdebug_bundle_counter);console.log("%c50recode: "+
isdebug_indent+"END "+message+obj,"color:"+color[isdebug_bundle_counter]+";");console.timeStamp("50recode: "+isdebug_indent+"END "+message);console.timeEnd("50recode: "+isdebug_indent+message);isdebug_indent=""}break;default:isdebug_indent=indent(isdebug_bundle_counter);console.log("50recode: "+isdebug_indent+message+obj);break}}}
INTELNAV.getParameterByName=function(name){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regexS="[\\?&]"+name+"=([^&#]*)";var regex=new RegExp(regexS);var results=regex.exec(window.location.href);if(results===null)return"";else return decodeURIComponent(results[1].replace(/\+/g," "))};
INTELNAV.query=function(){var _query=function(){var results={},q=location.search.replace(/^\?/,"").split("&"),i=0,split={};for(i=0;i<q.length;i++){split=q[i].split("=");results[split[0]]=split[1]}return results}();return function(name){if(typeof _query[name]==="undefined")return false;else if(_query[name].toLowerCase()=="true")return true;else if(_query[name].toLowerCase()=="false")return false;else return _query[name]}}();
INTELNAV.loadJS=function(filename){hf_debug("log","INTELNAV.loadJS = ",filename,2,isdebug);var fileref=document.createElement("script");fileref.setAttribute("type","text/javascript");fileref.setAttribute("src",filename);fileref.setAttribute("async","true");if(typeof fileref!=="undefined")document.getElementsByTagName("head")[0].appendChild(fileref)};
INTELNAV.loadStylesheet=function(path){var b=document.getElementsByTagName("head")[0],a=document.createElement("link"),c=document.createElement("meta");a.id="gaat-linkstyle";a.async=true;a.type="text/css";a.rel="stylesheet";a.href=path;b.appendChild(a)};INTELNAV.hc=INTELNAV.query("hc");INTELNAV.hcPath=INTELNAV.query("hcpath");
if(INTELNAV.hc&&!INTELNAV.hasrun){INTELNAV.hasrun=true;hf_debug("log","Switch headerchooser.js","",1,isdebug);if(typeof INTELNAV.hc=="boolean")INTELNAV.loadJS("https://proto.cps.intel.com/sites/sitewide/HAT/50recode/js/headerchooser-master.js");else switch(INTELNAV.hc){case "http://www.intel.com":case "https://www.intel.com":case "https://test-www.intel.com":case "https://www-ssl.intel.com":case "http://jgarber-mobl.amr.corp.intel.com":case "https://jgarber-mobl.amr.corp.intel.com":case "http://gadev":case "https://gadev":case "http://proto-cps.cps.intel.com":case "https://proto.cps.intel.com":case "http://preview-cps.cps.intel.com":INTELNAV.loadJS(INTELNAV.hc+
INTELNAV.hcPath);break;default:hf_debug("info","HC: This path is not approved! ("+INTELNAV.hc+INTELNAV.hcPath+")","",1,isdebug);break}}else{if(INTELNAV.hasrun)hf_debug("log","2nd headerchooser.js","",1,isdebug);(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date;a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics.js",
"ga");ga("create","UA-23487238-1","auto","ighf");ga("ighf.set","anonymizeIp",true);(function(home){hf_debug("bundletimestart","assetLoader-master.js: waitFor()","",2,isdebug);var w={delay:500,_queue:{},_count:0,_lastId:-1,_finalized:false,_log:function(s){if(typeof console!=="undefined"&&typeof console.log!=="undefined")console.log(s)},_timeout:function(){if(w._count>0){var q=w._queue;for(var key in q)if(q.hasOwnProperty(key))if(q[key].t()){hf_debug("log","waitFor: success triggered on entry "+key,
"",2,isdebug);q[key].s();w.remove(key)}}else if(w._finalized){hf_debug("log","waitFor: _timeout() terminating","",2,isdebug);return}w._timeoutId=setTimeout(w._timeout,w.delay)},_init:function(home){hf_debug("log","waitFor: _init() entered (delay:"+w.delay+"ms)","",2,isdebug);if(typeof home==="undefined")home=window;home.waitFor=w;w._timeout()},add:function(test,success){hf_debug("log","waitFor: add("+test+") entered (id:"+(w._lastId+1)+")","",2,isdebug);if(w._finalized){hf_debug("log","waitFor: add("+
test+") attempted after finalize","",2,isdebug);return}w._count+=1;w._lastId+=1;w._queue[w._lastId]={t:test,s:success};return w._lastId},remove:function(id){hf_debug("log","waitFor: remove() entered (id:"+id+")","",2,isdebug);if(w._queue.hasOwnProperty(id)){delete w._queue[id];w._count-=1}},finalize:function(){hf_debug("log","waitFor: finalize() entered","",2,isdebug);w._finalized=true}};w._init(home);hf_debug("bundletimeend","assetLoader-master.js: waitFor()","",2,isdebug)})(window);var wap_header=
{};wap_header.HeaderVersion="";wap_header.HeaderChosen="";wap_header.HeaderSubNav="";wap_header.HeaderGEO="";wap_header.FooterChosen="";wap_header.Locale="";INTELNAV.browserParameters={str:null,bN:null,bM:null,bV:null,OS:null,dT:null,wk:null,bvClass:null};INTELNAV.renderSettings.version?INTELNAV.renderSettings.version:INTELNAV.renderSettings.version="1.2 - 09/17/2013 01:01:01";var segment="",searchFilter="",isRWD="false";var isdebug=INTELNAV.getParameterByName("isdebug")||0;hf_debug("info","START HEADERCHOOSER",
"",2,isdebug);var IE11=INTELNAV.getParameterByName("IE11")||false;var forcetest=INTELNAV.getParameterByName("forcetest");if(forcetest!=""&&forcetest.indexOf("-")>=0)INTELNAV.forceTestObj=forcetest.split("-");else{if(typeof INTELNAV.dashboard!=="undefined"&&typeof INTELNAV.dashboard.environment!=="undefined")var tmpForceTest="unav-4-"+INTELNAV.dashboard.environment;else var tmpForceTest="unav-4-prod";hf_debug("log","tmpForceTest="+tmpForceTest,"",1,isdebug);INTELNAV.forceTestObj=tmpForceTest.split("-")}var menu=
0,design=1,env=2;hf_debug("log","INTELNAV.forceTestObj[]="+INTELNAV.forceTestObj[menu]+"-"+INTELNAV.forceTestObj[design]+"-"+INTELNAV.forceTestObj[env],"",1,isdebug);var RWD=INTELNAV.getParameterByName("RWD")||"";if(RWD!=="")isRWD=RWD;hf_debug("log","RWD="+RWD,"",2,isdebug);var isMin=".min";if(INTELNAV.getParameterByName("isMin"))isMin="";var disableGA=INTELNAV.getParameterByName("disableGA")||false;var disableWAP=INTELNAV.getParameterByName("disableWAP")||false;var GAAT40=GAAT40||{};GAAT40.renderSettings=
{};GAAT40.renderSettings=INTELNAV.renderSettings;var RollBack=false;INTELNAV.Cultures={unav:{ActiveCulturesFramework:"ar_AE|ar_EG|ar_SA|ar_XR|cs_CZ|de_DE|en_AP|en_AU|en_EU|en_HK|en_IE|en_IN|en_IR|en_MY|en_NZ|en_PH|en_PK|en_SA|en_SG|en_UK|en_US|en_XA|en_XE|en_XR|en_ZA|es_ES|es_LA|es_MX|es_XL|fr_FR|he_IL|hi_IN|hu_HU|id_ID|it_IT|ja_JP|ko_KR|nl_NL|pl_PL|pt_BR|ro_RO|ru_RU|sv_SE|th_TH|tr_TR|uk_UA|vi_VN|zh_CN|zh_TW|fw_FW"}};INTELNAV.recode50={unav:{design:"unav",firstDesign:4,currentDesign:4,4:{ActiveCultures:"ar_AE:ar_XR|ar_DZ:en_ZA|ar_EG:ar_XR|ar_MA:en_ZA|ar_SA:ar_XR|ar_XR:|cs_CZ:en_US|de_CH:de_DE|de_DE:|en_AE:en_XR|en_AP:en_XA|en_AU:|en_CA:|en_EG:en_XR|en_EU:en_US|en_HK:en_XA|en_IE:en_US|en_IN:|en_IR:en_IE|en_KE:en_ZA|en_MY:en_XA|en_NG:en_ZA|en_NZ:en_AU|en_PH:en_XA|en_PK:en_XA|en_SA:en_XR|en_SG:en_XA|en_UK:|en_US:|en_XA:|en_XE:en_UK|en_XR:|en_ZA:|es_AR:es_XL|es_CL:es_XL|es_CO:es_XL|es_ES:|es_LA:es_XL|es_MX:es_XL|es_XL:|fr_CA:fr_FR|fr_DZ:en_ZA|fr_FR:|fr_MA:en_ZA|he_IL:|hi_IN:en_IN|hu_HU:en_US|id_ID:|it_IT:|ja_JP:|ko_KR:|nl_NL:en_US|pl_PL:|pt_BR:|ro_RO:en_UK|ru_RU:|sv_SE:en_US|th_TH:|tr_TR:|uk_UA:ru_RU|vi_VN:|zh_CN:|zh_TW:|fw_3R:",
ActiveCultures_RWD:"ar_AE:ar_XR|ar_DZ:en_ZA|ar_EG:ar_XR|ar_MA:en_ZA|ar_SA:ar_XR|ar_XR:|cs_CZ:en_US|de_CH:de_DE|de_DE:|en_AE:en_XR|en_AP:en_XA|en_AU:|en_CA:|en_EG:en_XR|en_EU:en_US|en_HK:en_XA|en_IE:en_US|en_IN:|en_IR:en_IE|en_KE:en_ZA|en_MY:en_XA|en_NG:en_ZA|en_NZ:en_AU|en_PH:en_XA|en_PK:en_XA|en_SA:en_XR|en_SG:en_XA|en_UK:|en_US:|en_XA:|en_XE:en_UK|en_XR:|en_ZA:|es_AR:es_XL|es_CL:es_XL|es_CO:es_XL|es_ES:|es_LA:es_XL|es_MX:es_XL|es_XL:|fr_CA:fr_FR|fr_DZ:en_ZA|fr_FR:|fr_MA:en_ZA|he_IL:|hi_IN:en_IN|hu_HU:en_US|id_ID:|it_IT:|ja_JP:|ko_KR:|nl_NL:en_US|pl_PL:|pt_BR:|ro_RO:en_UK|ru_RU:|sv_SE:en_US|th_TH:|tr_TR:|uk_UA:ru_RU|vi_VN:|zh_CN:|zh_TW:|fw_3R:",
devPathHttp:"https://jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/50recode/designs/unav4/assets/js/assetLoader"+isMin+".js",devPathHttps:"https://jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/50recode/designs/unav4/assets/js/assetLoader"+isMin+".js",qaPathHttp:"https://proto.cps.intel.com/sites/sitewide/HAT/50recode/designs/unav4/assets/js/assetLoader"+isMin+".js",qaPathHttps:"https://proto.cps.intel.com/sites/sitewide/HAT/50recode/designs/unav4/assets/js/assetLoader"+isMin+".js",prevPathHttp:"http://preview-cps.cps.intel.com/sites/sitewide/HAT/50recode/designs/unav4/assets/js/assetLoader"+
isMin+".js",prevPathHttps:"http://preview-cps.cps.intel.com/sites/sitewide/HAT/50recode/designs/unav4/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/sites/sitewide/HAT/50recode/designs/unav4/assets/js/assetLoader"+isMin+".js",prodPathHttps:"https://www.intel.com/sites/sitewide/HAT/50recode/designs/unav4/assets/js/assetLoader"+isMin+".js"}},drc:{design:"drc",firstDesign:4,currentDesign:4,4:{ActiveCultures:"en_US:|nu_LL:",ActiveCultures_RWD:"en_US:|nu_LL:",devPathHttp:"http://jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/50recode/designs/drc4/assets/js/assetLoader"+
isMin+".js",devPathHttps:"https://jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/50recode/designs/drc4/assets/js/assetLoader"+isMin+".js",qaPathHttp:"https://proto.cps.intel.com/sites/sitewide/HAT/50recode/designs/drc4/assets/js/assetLoader"+isMin+".js",qaPathHttps:"https://proto.cps.intel.com/sites/sitewide/HAT/50recode/designs/drc4/assets/js/assetLoader"+isMin+".js",prevPathHttp:"http://preview-cps.cps.intel.com/sites/sitewide/HAT/50recode/designs/drc4/assets/js/assetLoader"+isMin+".js",prevPathHttps:"http://preview-cps.cps.intel.com/sites/sitewide/HAT/50recode/designs/drc4/assets/js/assetLoader"+
isMin+".js",prodPathHttp:"https://www.intel.com/sites/sitewide/HAT/50recode/designs/drc4/assets/js/assetLoader"+isMin+".js",prodPathHttps:"https://www.intel.com/sites/sitewide/HAT/50recode/designs/drc4/assets/js/assetLoader"+isMin+".js"}},intc:{design:"intc",firstDesign:4,currentDesign:4,4:{ActiveCultures:"en_US:|nu_LL:",ActiveCultures_RWD:"en_US:|nu_LL:",devPathHttp:"http://jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/50recode/designs/intc4/assets/js/assetLoader"+isMin+".js",devPathHttps:"https://jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/50recode/designs/intc4/assets/js/assetLoader"+
isMin+".js",qaPathHttp:"https://proto.cps.intel.com/sites/sitewide/HAT/50recode/designs/intc4/assets/js/assetLoader"+isMin+".js",qaPathHttps:"https://proto.cps.intel.com/sites/sitewide/HAT/50recode/designs/intc4/assets/js/assetLoader"+isMin+".js",prevPathHttp:"http://preview-cps.cps.intel.com/sites/sitewide/HAT/50recode/designs/intc4/assets/js/assetLoader"+isMin+".js",prevPathHttps:"http://preview-cps.cps.intel.com/sites/sitewide/HAT/50recode/designs/intc4/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/sites/sitewide/HAT/50recode/designs/intc4/assets/js/assetLoader"+
isMin+".js",prodPathHttps:"https://www.intel.com/sites/sitewide/HAT/50recode/designs/intc4/assets/js/assetLoader"+isMin+".js"}},swdevcon:{design:"swdevcon",firstDesign:4,currentDesign:4,4:{ActiveCultures:"en_US:|ja_JP:|ko_KR:|nu_LL:",ActiveCultures_RWD:"en_US:|ja_JP:|ko_KR:|nu_LL:",devPathHttp:"http://jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/50recode/designs/swdevcon4/assets/js/assetLoader"+isMin+".js",devPathHttps:"https://jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/50recode/designs/swdevcon4/assets/js/assetLoader"+
isMin+".js",qaPathHttp:"https://proto.cps.intel.com/sites/sitewide/HAT/50recode/designs/swdevcon4/assets/js/assetLoader"+isMin+".js",qaPathHttps:"https://proto.cps.intel.com/sites/sitewide/HAT/50recode/designs/swdevcon4/assets/js/assetLoader"+isMin+".js",prevPathHttp:"http://preview-cps.cps.intel.com/sites/sitewide/HAT/50recode/designs/swdevcon4/assets/js/assetLoader"+isMin+".js",prevPathHttps:"http://preview-cps.cps.intel.com/sites/sitewide/HAT/50recode/designs/swdevcon4/assets/js/assetLoader"+isMin+
".js",prodPathHttp:"https://www.intel.com/sites/sitewide/HAT/50recode/designs/swdevcon4/assets/js/assetLoader"+isMin+".js",prodPathHttps:"https://www.intel.com/sites/sitewide/HAT/50recode/designs/swdevcon4/assets/js/assetLoader"+isMin+".js"}},inteldroneracing:{design:"inteldroneracing",firstDesign:4,currentDesign:4,4:{ActiveCultures:"en_US:|es_XL:|pt_BR:|nu_LL:",ActiveCultures_RWD:"en_US:|es_XL:|pt_BR:|nu_LL:",devPathHttp:"http://jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/50recode/designs/inteldroneracing4/assets/js/assetLoader"+
isMin+".js",devPathHttps:"https://jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/50recode/designs/inteldroneracing4/assets/js/assetLoader"+isMin+".js",qaPathHttp:"https://proto.cps.intel.com/sites/sitewide/HAT/50recode/designs/inteldroneracing4/assets/js/assetLoader"+isMin+".js",qaPathHttps:"https://proto.cps.intel.com/sites/sitewide/HAT/50recode/designs/inteldroneracing4/assets/js/assetLoader"+isMin+".js",prevPathHttp:"http://preview-cps.cps.intel.com/sites/sitewide/HAT/50recode/designs/inteldroneracing4/assets/js/assetLoader"+
isMin+".js",prevPathHttps:"http://preview-cps.cps.intel.com/sites/sitewide/HAT/50recode/designs/inteldroneracing4/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/sites/sitewide/HAT/50recode/designs/inteldroneracing4/assets/js/assetLoader"+isMin+".js",prodPathHttps:"https://www.intel.com/sites/sitewide/HAT/50recode/designs/inteldroneracing4/assets/js/assetLoader"+isMin+".js"}}};var ActiveCulturesFramework=INTELNAV.Cultures.unav.ActiveCulturesFramework;var ActiveCultures4=INTELNAV.recode50.unav["4"].ActiveCultures;
var ActiveCultures4_RWD=INTELNAV.recode50.unav["4"].ActiveCultures_RWD;INTELNAV.assetPathHttp="https://www.intel.com";INTELNAV.assetPathHttps="https://www.intel.com";INTELNAV.assetServer="https://www.intel.com";INTELNAV.UrlLookUpTable={urls:[{site:"simplecore-dev.intel.com/drc",menu:"drc",design:"4",RWD:"true"},{site:"drc.intel.com|simplecore-dev.intel.com/drc|marketingcentral-dev.intel.com|marketingcentral.intel.com",menu:"drc",design:"4",RWD:"true"},{site:"intel2016ir.q4web.com|www.intc.com",menu:"intc",
design:"4",RWD:"true"},{site:"intel2016ir.q4web.com|www.intc.com",menu:"intc",design:"4",RWD:"true"},{site:"simplecore-dev.intel.com/inteldroneracing(|-lar|-pt)",menu:"inteldroneracing",design:"4",RWD:"true",root:"inteldroneracing",SSO:{mode:"Generic",signOutPath:"href='#'",myProfilePath:"",signInPath:"href='https://www.intel.com/content/www/us/en/my-intel/reseller-login.html'",signIn:true}},{site:"downloadcenter(01|02|)-(dev|tst|prd|dr).intel.com",design:"4",RWD:"true",searchFilter:[{sf_var:"topicarea",
sf_val:"Downloads"}]},{site:"downloadcenter(|-origin).intel.com",design:"4",RWD:"true",searchFilter:[{sf_var:"topicarea",sf_val:"Downloads"}]},{site:"(edc.intel.com|preview-edc.intel.com|inteledcpreviewapp.azurewebsites.net)",design:"4",searchFilter:[{sf_var:"progId",sf_val:"irdc"},{sf_var:"EDCProgramIdentifier",sf_val:"true"}]},{site:"(isvcqa2-intelcustomersupport.cs10.force.com|isvcqa2-intelcustomersupport.cs10.intel.com|dev02-intelcustomersupport.cs20.force.com)",design:"4",RWD:"true",SSO:{mode:"Generic",
signOutPath:"href='/secur/logout.jsp'",myProfilePath:"",signInPath:"href='https://sfederationpreprod.intel.com/federation/Init_salesforce_isvc_qa2_portal.asp'",signIn:true}},{site:"(isvcdev07-intelcustomersupport.cs21.force.com|isvcqa-intelcustomersupport.cs21.force.com|intelcustomersupport.force.com|customercare.intel.com|supporttickets.intel.com)",design:"4",RWD:"true",SSO:{mode:"Generic",signOutPath:"href='/secur/logout.jsp'",myProfilePath:"",signInPath:"href='https://sfederation.intel.com/federation/Init_Salesforce_ISVC.asp'",
signIn:true}},{site:"proto-cps.cps.intel.com/sites/sitewide/HAT/testharness/50recode/*IGHFtest=drc-4-dev|jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/testharness/50recode/*forcetest=drc-4-dev|*IGHFtest=inteldroneracing-4-qa",menu:"inteldroneracing",design:"4",RWD:"true",SSO:{mode:"Generic",signOutPath:"href='#'",myProfilePath:"",signInPath:"href='https://www.intel.com/content/www/us/en/my-intel/reseller-login.html'",signIn:true}},{site:"proto-cps.cps.intel.com/sites/sitewide/HAT/testharness/50recode|jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/testharness/50recode|proto.cps.intel.com/sites/sitewide/HAT/testharness/50recode",
menu:"unav",env:"qa",design:"4",RWD:"true",SSO:{mode:"Generic",signOutPath:"href='https://supporttickets.intel.com/secur/logout.jsp'",myProfilePath:"",signInPath:"href='https://sfederation.intel.com/federation/Init_Salesforce_ISVC.asp'",signIn:true}},{site:"localhost",design:"4",RWD:"true"}]};INTELNAV.oldBrowserDetect=function(){var BrowserMode=document.compatMode=="CSS1Compat"?"Standards":"Quirks";var str=navigator.appVersion.toLowerCase().replace(/[^a-zA-Z 0-9 . / _]+/g,"").split(" ");deviceType=
str[1].substr(0,3);if(/MSIE\s([\d.]+)/.test(navigator.userAgent)){var version=new Number(RegExp.$1);INTELNAV.browser={Name:"ie",Version:version,Mode:BrowserMode};switch(parseInt(version)){case 9:document.documentElement.className+=" lt-ie10";document.body.className+=deviceType+" ie ie9_0";break;case 8:document.documentElement.className+=" lt-ie10 lt-ie9";document.body.className+=deviceType+" ie ie8_0";break;case 7:document.documentElement.className+=" lt-ie10 lt-ie9 lt-ie8";document.body.className+=
deviceType+" ie ie7_0";break;case 6:document.documentElement.className+=" lt-ie10 lt-ie9 lt-ie8 lt-ie7";document.body.className+=deviceType+" ie ie6_0";break;default:break}}else INTELNAV.browser={Name:"",Version:0,Mode:BrowserMode}};INTELNAV.oldBrowserDetect();(function(){hf_debug("timestart","TOTALLOADTIME","",1,isdebug);hf_debug("bundletimestart","headerchooser.js: (function(){})","",2,isdebug);if(INTELNAV.getParameterByName("pageWidth")!=="")INTELNAV.renderSettings.pageWidth=INTELNAV.getParameterByName("pageWidth");
if(INTELNAV.getParameterByName("textDirection")!=="")INTELNAV.renderSettings.textDirection=INTELNAV.getParameterByName("textDirection");if(INTELNAV.getParameterByName("protocol")!=="")INTELNAV.renderSettings.protocol=INTELNAV.getParameterByName("protocol");if(INTELNAV.getParameterByName("culture")!=="")INTELNAV.renderSettings.culture=INTELNAV.getParameterByName("culture");if(INTELNAV.getParameterByName("buildType")!=="")INTELNAV.renderSettings.buildType=INTELNAV.getParameterByName("buildType");if(INTELNAV.getParameterByName("OutputId")!==
"")INTELNAV.renderSettings.OutputId=INTELNAV.getParameterByName("OutputId");var secure=INTELNAV.renderSettings.protocol=="https";INTELNAV.culture=INTELNAV.renderSettings.culture.toUpperCase();INTELNAV.baseCulture=INTELNAV.culture;switch(INTELNAV.culture){case "EN_XR":INTELNAV.renderSettings.textDirection="ltr";break;case "AR_DZ":case "AR_MA":INTELNAV.renderSettings.textDirection="rtl";break;default:break}var outputid=INTELNAV.renderSettings.OutputId;hf_debug("log","HTTPS="+secure,"",1,isdebug);hf_debug("log",
"CULTURE="+INTELNAV.culture,"",1,isdebug);hf_debug("log","OUTPUTID="+outputid,"",1,isdebug);hf_debug("log","boxmodel="+document.compatMode,"",1,isdebug);INTELNAV.processUNAVgeos=function(){var getAltGeo=function(thisGeo,listOfGeos){var curGEO=thisGeo;var altGEO="";for(j=0;j<listOfGeos.length;j++){thisSplitGEO=listOfGeos[j].split(":");if(curGEO==thisSplitGEO[0])if(thisSplitGEO[1]!=null&&thisSplitGEO[1]!="undefined"&&thisSplitGEO[1]!=""){altGEO=thisSplitGEO[1];hf_debug("log","ALT CULTURE="+altGEO,"",
1,isdebug)}}return altGEO};INTELNAV.renderSettings.origCulture=INTELNAV.culture;var listOfGeos=INTELNAV.activeCultures.split("|");retGEO=getAltGeo(INTELNAV.renderSettings.culture,listOfGeos);if(retGEO!=""){INTELNAV.culture=retGEO;INTELNAV.culture=INTELNAV.culture.toUpperCase();hf_debug("log","NEW CULTURE="+INTELNAV.culture,"",1,isdebug)}};INTELNAV.initBuild=function(){hf_debug("bundletimestart","headerchooser.js: INTELNAV.initBuild()","",2,isdebug);var currentPageUrl=document.location.href;var targetEnvironmentForUrl=
{};var detectIE8=false;INTELNAV.domainLookUp=function(){var LUT=INTELNAV.UrlLookUpTable.urls;hf_debug("log","forcetest-notempty[1]="+forcetest,"",2,isdebug);var lutlength=LUT.length;if(lutlength>0&&RollBack==false){hf_debug("log","LUT.length="+lutlength,"",2,isdebug);for(var i=0;i<lutlength;i++){var myregexp=new RegExp("^https?:\\/\\/"+LUT[i].site.replace(/\./g,"\\.").replace(/\?(?!!)/g,"\\?").replace(/\*/g,".+")+".*","i");hf_debug("log","i="+i+"   regex="+myregexp,"",2,isdebug);if(myregexp.test(currentPageUrl)){hf_debug("log",
"LUT Match Found","",1,isdebug);hf_debug("log","LUT Match Found("+myregexp+")","",2,isdebug);if(!forcetest){if(typeof LUT[i].menu!=="undefined")INTELNAV.forceTestObj[menu]=LUT[i].menu;hf_debug("log","MENU(MAPPED)="+INTELNAV.forceTestObj[menu],"",1,isdebug);if(typeof LUT[i].env!=="undefined")INTELNAV.forceTestObj[env]=LUT[i].env;hf_debug("log","ENVIRONMENT(MAPPED)="+INTELNAV.forceTestObj[env],"",1,isdebug);INTELNAV.forceTestObj[design]=parseInt(LUT[i].design);hf_debug("log","DESIGN(MAPPED)="+INTELNAV.forceTestObj[design],
"",1,isdebug);hf_debug("log","CULTURE(MAPPED)="+INTELNAV.culture,"",1,isdebug);targetEnvironmentForUrl=LUT[i]}INTELNAV.LUT=LUT[i];document.getElementById("recode50header").className="recode50unav";break}}}};INTELNAV.domainLookUp();hf_debug("log","INTELNAV.forceTestObj[]="+INTELNAV.forceTestObj[menu]+"-"+INTELNAV.forceTestObj[design]+"-"+INTELNAV.forceTestObj[env],"",2,isdebug);if(!Object.keys)Object.keys=function(){var hasOwnProperty=Object.prototype.hasOwnProperty,hasDontEnumBug=!{toString:null}.propertyIsEnumerable("toString"),
dontEnums=["toString","toLocaleString","valueOf","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","constructor"],dontEnumsLength=dontEnums.length;return function(obj){if(typeof obj!=="object"&&(typeof obj!=="function"||obj===null))throw new TypeError("Object.keys called on non-object");var result=[],prop,i;for(prop in obj)if(hasOwnProperty.call(obj,prop))result.push(prop);if(hasDontEnumBug)for(i=0;i<dontEnumsLength;i++)if(hasOwnProperty.call(obj,dontEnums[i]))result.push(dontEnums[i]);return result}}();
INTELNAV.validateMenu=function(){var menuObj=INTELNAV.recode50;var tmpMenu=INTELNAV.forceTestObj[menu];var keys=Object.keys(menuObj);var keysLength=keys.length;for(var i=0,keys;i<keysLength;i++)if(keys[i]==INTELNAV.forceTestObj[menu]){hf_debug("log","validateMenu(): iMenu("+keys[i]+") = FOUND "+INTELNAV.recode50[keys[i]],"",2,isdebug);tmpMenu=keys[i];break}else tmpMenu="";return tmpMenu};INTELNAV.validateDesign=function(){var designObj=INTELNAV.recode50[INTELNAV.forceTestObj[menu]];var tmpDesign=
-1;var keys=Object.keys(designObj);var keysLength=keys.length;for(var i=0,keys;i<keysLength;i++)if(keys[i]==INTELNAV.forceTestObj[design]){hf_debug("log","validateDesign(): INTELNAV.forceTestObj[menu]("+INTELNAV.forceTestObj[menu]+"); iDesign("+keys[i]+") = FOUND "+designObj[keys[i]],"",2,isdebug);tmpDesign=keys[i];break}else tmpDesign=-1;return tmpDesign};INTELNAV.getDesignData=function(){targetEnvironmentForUrl.defaultPathHttp=INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]][INTELNAV.forceTestObj[env]+
"PathHttp"];targetEnvironmentForUrl.defaultPathHttps=INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]][INTELNAV.forceTestObj[env]+"PathHttps"];hf_debug("log","getDesignData(): targetEnvironmentForUrl(2).defaultPathHttp="+targetEnvironmentForUrl.defaultPathHttp,"",2,isdebug);hf_debug("log","getDesignData(): targetEnvironmentForUrl(2).defaultPathHttps="+targetEnvironmentForUrl.defaultPathHttps,"",2,isdebug)};INTELNAV.designFallbackByGeoMatch=function(){var count=0;var geoMatch=
false;var tmpDesign=INTELNAV.forceTestObj[design];if(INTELNAV.browser.Name=="ie"&&(INTELNAV.browser.Version=="8.0"||INTELNAV.browser.Version=="7.0"||INTELNAV.browser.Version=="6.0")){detectIE8=true;hf_debug("log","detectIE8",detectIE8,1,isdebug)}while(!geoMatch){hf_debug("log","menu="+INTELNAV.forceTestObj[menu],"",2,isdebug);hf_debug("log","tmpDesign="+tmpDesign,"",2,isdebug);hf_debug("log","INTELNAV.Cultures="+INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign],"",2,isdebug);hf_debug("log",
"firstDesign="+parseInt(INTELNAV.recode50[INTELNAV.forceTestObj[menu]]["firstDesign"]),"",2,isdebug);if(typeof INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign]!=="undefined")if(typeof INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign]["ActiveCultures"]!=="undefined"){INTELNAV.activeCultures=INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign]["ActiveCultures"];INTELNAV.processUNAVgeos();hf_debug("log","parseInt(INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign]['ActiveCultures']['firstDesign'])",
INTELNAV.recode50[INTELNAV.forceTestObj[menu]]["firstDesign"],2,isdebug);if(INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign]["ActiveCultures"].toUpperCase().search(INTELNAV.culture)!==-1){geoMatch=true;hf_debug("log","designFallbackByGeoMatch(3a)="+tmpDesign,"",2,isdebug);hf_debug("log","DESIGN("+tmpDesign+")=GEO("+INTELNAV.culture+") Match Found!","",1,isdebug)}else if(tmpDesign==parseInt(INTELNAV.recode50[INTELNAV.forceTestObj[menu]]["firstDesign"])){INTELNAV.culture="en_US";tmpDesign=
INTELNAV.forceTestObj[design];geoMatch=true;hf_debug("log","designFallbackByGeoMatch(4)="+tmpDesign,"",2,isdebug);hf_debug("log","##teamcity[message text='GEO("+INTELNAV.baseCulture+") not found in DESIGN("+tmpDesign+")' errorDetails='GEO("+INTELNAV.baseCulture+") not found in DESIGN("+tmpDesign+")' status='FAILURE'] ","",1,isdebug);hf_debug("log","Resetting to DESIGN("+tmpDesign+"), GEO("+INTELNAV.culture+") ","",1,isdebug)}else{tmpDesign--;hf_debug("log","designFallbackByGeoMatch(5)="+tmpDesign,
"",1,isdebug);hf_debug("log","##teamcity[message text='GEO("+INTELNAV.baseCulture+") not found in DESIGN("+tmpDesign+"), falling back' errorDetails='GEO("+INTELNAV.baseCculture+") not found in DESIGN("+tmpDesign+"), falling back' status='FAILURE'] ","",1,isdebug);hf_debug("log","DESIGN("+tmpDesign+")=GEO("+INTELNAV.culture+") Not Found, falling back","",1,isdebug)}}else tmpDesign--;else tmpDesign--;count++;if(count>20){geoMatch=true;hf_debug("log","designFallbackByGeoMatch(>10)="+tmpDesign,"",2,isdebug)}}INTELNAV.forceTestObj[design]=
tmpDesign};hf_debug("log","MENU(MAPPED2)="+INTELNAV.forceTestObj[menu],"",1,isdebug);hf_debug("log","DESIGN(MAPPED2)="+INTELNAV.forceTestObj[design],"",1,isdebug);hf_debug("log","CULTURE(MAPPED2)="+INTELNAV.culture,"",1,isdebug);if(typeof INTELNAV.recode50[INTELNAV.forceTestObj[menu]]!=="undefined"){hf_debug("log","INTELNAV.forceTestObj[menu]("+INTELNAV.forceTestObj[menu]+") = VALID","",1,isdebug);if((INTELNAV.forceTestObj[design]=INTELNAV.validateDesign())>=0){hf_debug("log","INTELNAV.forceTestObj[design]("+
INTELNAV.forceTestObj[design]+") = VALID","",2,isdebug);INTELNAV.designFallbackByGeoMatch();hf_debug("log","MENU(MAPPED3)="+INTELNAV.forceTestObj[menu],"",1,isdebug);hf_debug("log","DESIGN(MAPPED3)="+INTELNAV.forceTestObj[design],"",1,isdebug);hf_debug("log","CULTURE(MAPPED3)="+INTELNAV.culture,"",1,isdebug);INTELNAV.getDesignData();switch(INTELNAV.forceTestObj[menu]){case "mcafee":break;case "drc":case "unav":default:if(INTELNAV.forceTestObj[design]==2){hf_debug("log","forcetest-design[2]="+forcetest,
"",2,isdebug);if(INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]]["ActiveCultures"].toUpperCase().search(INTELNAV.culture)!==-1){hf_debug("log","DESIGN(INIT)="+INTELNAV.forceTestObj[design],"",2,isdebug);if(typeof targetEnvironmentForUrl.isVisible!=="undefined"){segment="-"+targetEnvironmentForUrl.isVisible;if(segment=="-footeronly"){document.getElementById("recode50header").className+=" u-nav-hidden ";document.getElementById("recode50header").style.display="none";document.getElementById("recode50footer").className+=
" small "}}else segment="-both";hf_debug("log","SEGMENT="+segment,"",2,isdebug);if(typeof targetEnvironmentForUrl.searchFilter!=="undefined")searchFilter=targetEnvironmentForUrl.searchFilter;hf_debug("log","searchFilter="+searchFilter,"",2,isdebug)}}else if(INTELNAV.forceTestObj[design]==3||INTELNAV.forceTestObj[design]==4){hf_debug("log","forcetest-design[3+4]="+forcetest,"",2,isdebug);if(INTELNAV.browser.Name=="ie"&&INTELNAV.browser.Version=="7.0"){detectIE8=true;hf_debug("log","detectIE8",detectIE8,
1,isdebug);hf_debug("log","enable HTML5 objects for IE8","",1,isdebug);document.createElement("header");document.createElement("section");document.createElement("article");document.createElement("aside");document.createElement("nav");document.createElement("footer")}if(INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]]["ActiveCultures"].toUpperCase().search(INTELNAV.culture)!==-1&&detectIE8==false){hf_debug("log","DESIGN(INIT)="+INTELNAV.forceTestObj[design],"",2,isdebug);
if(typeof INTELNAV.dashboard!=="undefined"&&typeof INTELNAV.dashboard.isVisible!=="undefined")segment=INTELNAV.dashboard.isVisible;if(typeof targetEnvironmentForUrl.isVisible!=="undefined")segment="-"+targetEnvironmentForUrl.isVisible;if(segment=="-footeronly"){document.getElementById("recode50header").className+=" u-nav-hidden ";document.getElementById("recode50header").style.display="none";document.getElementById("recode50footer").className+=" small "}else segment="-both";hf_debug("log","SEGMENT="+
segment,"",1,isdebug);if(typeof targetEnvironmentForUrl.searchFilter!=="undefined")searchFilter=targetEnvironmentForUrl.searchFilter;hf_debug("log","searchFilter="+searchFilter,"",2,isdebug);if(typeof targetEnvironmentForUrl.RWD!=="undefined"&&typeof INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]]["ActiveCultures_RWD"]!=="undefined"){if(INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]]["ActiveCultures_RWD"].toUpperCase().search(INTELNAV.culture)!==
-1){INTELNAV.activeCultures=INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]]["ActiveCultures_RWD"];isRWD=targetEnvironmentForUrl.RWD}}else if(INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]]["ActiveCultures"].toUpperCase().search(INTELNAV.culture)!==-1){INTELNAV.activeCultures=INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]]["ActiveCultures"];isRWD="false"}if(RWD!=="")isRWD=RWD;hf_debug("log","isRWD="+isRWD,"",
1,isdebug)}}isRWD="true";break}INTELNAV.renderSettings.culture=INTELNAV.culture;INTELNAV.assetPathHttp=targetEnvironmentForUrl.defaultPathHttp;INTELNAV.assetPathHttps=targetEnvironmentForUrl.defaultPathHttps;hf_debug("log","INTELNAV.assetPathHttp="+INTELNAV.assetPathHttp,"",2,isdebug);hf_debug("log","INTELNAV.assetPathHttps="+INTELNAV.assetPathHttps,"",2,isdebug);assetPath=secure?INTELNAV.assetPathHttps:INTELNAV.assetPathHttp;var rx;rx=/(https?:\/\/[-\w.]+)+(:\d+)?(\/)?/;matches=assetPath.match(rx);
if(matches!==null){host=matches[0];if(host.charAt(host.length-1)=="/")host=host.slice(0,-1)}INTELNAV.assetServer=host;hf_debug("log","INTELNAV.assetServer="+INTELNAV.assetServer,"",2,isdebug);function loadJS3(filename){hf_debug("log","loadJS = ",filename,2,isdebug);var fileref=document.createElement("script");fileref.setAttribute("type","text/javascript");fileref.setAttribute("src",filename);fileref.setAttribute("async","true");if(typeof fileref!="undefined")document.getElementsByTagName("head")[0].appendChild(fileref)}
loadJS3(assetPath);hf_debug("bundletimeend","headerchooser.js: INTELNAV.initBuild()","",2,isdebug)}else hf_debug("log","INTELNAV.forceTestObj[design]("+INTELNAV.forceTestObj[design]+") = NOT FOUND ","",2,isdebug)}else hf_debug("log","INTELNAV.forceTestObj[menu]("+INTELNAV.forceTestObj[menu]+") = NOT FOUND ","",2,isdebug);hf_debug("log","======================================","",2,isdebug)};INTELNAV.initBuild();hf_debug("log","testtest","",2,isdebug);window.waitFor.add(function(){return typeof INTELNAV.renderSettingsFooter!==
"undefined"},function(){hf_debug("log","waitFor: typeof INTELNAV.renderSettingsFooter.OutputId !== 'undefined'","",2,isdebug);var HeaderType=INTELNAV.forceTestObj[menu]+INTELNAV.forceTestObj[design]+INTELNAV.forceTestObj[env];if(document.compatMode=="BackCompat")HeaderType=HeaderType+"(Quirks)";if(INTELNAV.renderSettings.protocol=="https")HeaderType=HeaderType+"("+INTELNAV.renderSettings.protocol.toUpperCase()+")";hf_debug("log","HeaderType="+HeaderType,"",1,isdebug);var patrn=/\d+(\.\d+)+/g;var str=
INTELNAV.renderSettings.version;var myArray=str.match(patrn);var frameworkShortVersion=myArray[0];hf_debug("log","frameworkShortVersion="+frameworkShortVersion,"",1,isdebug);hf_debug("log","50recode."+frameworkShortVersion,"",1,true);ga("ighf.set","dimension1","50recode."+frameworkShortVersion);ga("ighf.set","dimension2",INTELNAV.renderSettings.version);ga("ighf.set","dimension3",HeaderType);ga("ighf.set","dimension4",outputid);ga("ighf.set","dimension5",INTELNAV.culture);ga("ighf.set","dimension6",
INTELNAV.renderSettingsFooter.OutputId);ga("ighf.set","dimension7","renderMode:"+INTELNAV.renderSettings.renderMode+".protocol:"+INTELNAV.renderSettings.protocol+".pageWidth:"+INTELNAV.renderSettings.pageWidth+".INT.50recode");if(!disableGA)ga("ighf.send","pageview");wap_header.HeaderVersion="INT.50recode";wap_header.HeaderChosen=HeaderType+".INT.50recode";wap_header.HeaderSubNav=outputid+"."+HeaderType+".INT.50recode";wap_header.HeaderGEO=INTELNAV.culture+"."+HeaderType+".INT.50recode";wap_header.FooterChosen=
INTELNAV.renderSettingsFooter.OutputId+"."+HeaderType+".INT.50recode";var lang_sel=INTELNAV.culture;var tms_loc=lang_sel==="undefined"?"en_us":lang_sel.toLowerCase();var strLocale=tms_loc.split("_");var wa_country=strLocale[1];var wa_language=strLocale[0];wap_header.Locale=wa_country+"-"+wa_language});hf_debug("bundletimeend","headerchooser.js: (function(){})","",2,isdebug)})();function sectionOn(){}function hideAllMenus(){}function writeMenus(){}};
