steal.loading('nasdaq/media_player/media_player.js','jquery/controller/controller.js','jquery/view/ejs/ejs.js','jquery/controller/view/view.js','jquery/model/model.js','lib/utilities/utilities.js','lib/microsoft-playerframework/silverlight.js','lib/swfobject/swfobject.js','jquery/class/class.js','jquery/lang/string/string.js','jquery/event/destroyed/destroyed.js','jquery/event/event.js','jquery/view/view.js','jquery/lang/string/rsplit/rsplit.js','lib/jquery-jqplugin/jquery-jqplugin.js','lib/jquery-media/jquery-media.js','lib/jquery-strobemediaplayback/jquery-strobemediaplayback.js');
steal( /* {src:"jquery",ignore:true}, */ "jquery/controller","jquery/view/ejs","jquery/controller/view","jquery/model","lib/utilities","lib/microsoft-playerframework/silverlight.js","lib/swfobject").then("lib/jquery-jqplugin","lib/jquery-media","lib/jquery-strobemediaplayback",function(b){b.Controller("Nasdaq.MediaPlayer",{defaults:{width:360,height:240,src:undefined,poster:"",mediaType:undefined,flashPlayerPath:"lib/jquery-strobemediaplayback/NasdaqFlashPlayer.swf",
silverlightPlayerPath:"lib/microsoft-playerframework/ProgressiveDownloadPlayer.xap",autoPlay:false}},{init:function(){this.setupAsxUrl="/event/dragonbeta/setup.asx";this.playerElementId=util.generateUniqueId(10,"nsdqMedia_");this.playerState=undefined;this.html5VideoStarted=false;this.visible=true;var a=b(this.element).width();if(this.options.width==undefined)this.options.width=a;if(this.options.width==0)this.options.width=10;a=b(this.element).height();if(this.options.height==undefined)this.options.height=
a;if(this.options.height==0)this.options.height=10;this.currentPlayer="";this.createMediaPlayer()},createMediaPlayer:function(){if(this.options.src==undefined||this.options.src.length==0)alert("Error with media source URL.");else{var a=this.options.src;if(this.options.mediaType==undefined){this.options.mediaType=this.autoDetectFormat(a);if(this.options.mediaType==undefined){alert("Media type cannot be determined.");return}}var f=this.options.mediaType;if(this.confirmPlugin()!=false){var k=b(this.element),
w=this.options.width,E=this.options.height,x=this.options.autoPlay,C=b("<div></div>");this.mediaContainerId=util.generateUniqueId(10,"nsdqMediaContainer_");b(C).attr("id",this.mediaContainerId);b(C).width(w);b(C).height(E);k.append(b(C));var z=this.playerElementId;this.isWindowsMediaPlayer=false;var I=this,n=b("<div></div>");b(n).attr("id",z);if(f=="flash")if(util.supports_flash()){this.options.mediaType="flash";var h=this.options.flashPlayerPath;if(h.indexOf("http")==-1)h=util.getHost()+h;a=escape(a);
var j={id:z,src:a,width:w,height:E,autoPlay:x,allowScriptAccess:"always",bufferingOverlay:false,wmode:"opaque",poster:this.options.poster,swf:h+"?autostart="+x+"&htmlelementid="+this.element.attr("id"),favorFlashOverHtml5Video:true,javascriptCallbackFunction:"onJavaScriptBridgeCreated"};b(C).append(b(n));b(n).strobemediaplayback(j);I.element.addClass("flashControl")}else h="Your browser does not support Flash.";h="";if(f=="html5")if(util.supports_video()){this.options.mediaType="html5";j={src:a,width:w,
height:E,useHTML5:true,autoPlay:x,preload:"auto",poster:this.options.poster,bufferingOverlay:false,favorFlashOverHtml5Video:false,id:z,javascriptCallbackFunction:"onJavaScriptBridgeCreated"};b(C).append(b(n));b(n).strobemediaplayback(j)}else h="Your browser does not support HTML5 Video.";if(f=="win"){n=true;if(util.getScheme(window.location.href)=="https"&&util.getScheme(a)=="http")n=false;if(util.supports_silverlight()&&n){this.currentPlayer="silverlight";this.element.addClass("silverlightControl");
x="autoplay="+x+",scriptablename=sPlayer,bufferingtime=0:0:2,loggingenabled=true,mediaurl="+a;n=document.getElementById(this.mediaContainerId);j=this.options.silverlightPlayerPath;if(j.indexOf("http")==-1)j=util.getHost()+j;Silverlight.createObjectEx({source:j,parentElement:n,id:z,properties:{width:w,height:E,inplaceInstallPrompt:true,background:"transparent",isWindowless:this.isWindowsLessMedia(),framerate:"24",version:"2.0"},events:{onError:function(g,p){util.log("Silverlight Error - "+p.ErrorType+
" "+p.ErrorCode+" "+p.ErrorMessage)},onLoad:function(){util.log("Silverlight Loaded event.")}},initParams:x,context:null})}else if(util.supports_win()){this.element.addClass("wmpControl");this.options.mediaType="win";this.isWindowsMediaPlayer=true;b.fn.media.mapFormat("mp4","winmedia");n=this.isWindowsLessMedia();b(C).media({width:w,height:E,autoplay:x,standards:false,src:this.setupAsxUrl,attrs:{id:z},params:{uiMode:"full",ShowControls:"true",ShowStatusBar:"true",ShowDisplay:"true",windowlessVideo:n},
caption:false})}else h="Your browser does not support Windows Media Player Video."}if(h.length>0){h+=" You may not be able to see the media associated with this event.<br/><br/>Please <a href=''>go here for assistance</a>.";w=b("<div></div>");w.html(h);w.css("padding",20);C.append(w);k.css("border","solid 1px #666666");k.css("visibility","visible")}I=this;var d=this.getPlayerRef();if(f=="win"&&this.isWindowsMediaPlayer){if(d!=null&&d.settings&&d.settings.invokeURLs)d.settings.invokeURLs=false;setTimeout(function(){d.URL=
a},600)}this.element.css("visibility","visible");setTimeout(function(){I.attachListeners()},300)}}},autoDetectFormat:function(a){var f=undefined;if(a.indexOf("youtube")!=-1)f="flash";if(a.indexOf("rtmp")!=-1)f="flash";if(a.indexOf(".flv")!=-1)f="flash";if(a.indexOf(".mp4")!=-1)f="flash";if(a.indexOf(".asx")!=-1)f="win";if(a.indexOf(".wmv")!=-1)f="win";if(a.indexOf(".wma")!=-1)f="win";if(a.indexOf(".ogg")!=-1)f="html5";return f},confirmPlugin:function(){var a=false,f="";if(this.options.mediaType==
"flash"&&jQuery.browser.flash)a=true;else f="Flash Player";if(this.options.mediaType=="win"&&jQuery.browser.wmp)a=true;else f="Windows Media Player";if(this.options.mediaType=="html5"&&util.supports_h264_baseline_video())a=true;else f="HTML 5 Video";a||this.element.html("This content requires "+f+" support.");return a},mediaCommandHandler:function(){},onWinMediaLoaded:function(a,f,k){if(k=="playing"){b(this.element).unbind("player_state_change","onWinMediaLoaded");this.resizeTime!=undefined&&this.resizeTime>
0&&this.currentTime(this.resizeTime);this.resizeTime=0}},isWindowsLessMedia:function(){return b.browser.msie||b.browser.webkit?true:false},attachListeners:function(){if(this.currentPlayer!="silverlight"){var a=this.getPlayerRef();try{b(a).bind("statechange","onPlayerStateChange");var f=this;b.browser.msie?a.attachEvent("PlayStateChange",function(w){f.onPlayerStateChange(w)}):b(a).bind("playStateChange","onPlayerStateChange");this.bind(b(this.element),"player_state_change","onWinMediaLoaded");b(a).bind("playing",
function(){f.onPlayerStateChange()});b(a).bind("play",function(){f.onPlayerStateChange()});b(a).bind("pause",function(){f.onPlayerStateChange()})}catch(k){}}this.loaded()},onJavaScriptBridgeCreated:function(){var a=this.getPlayerRef();a.addEventListener("stateChange","onPlayerStateChange");a.addEventListener("markerReached","onMarkerReached")},setSilverlightPlayerRef:function(a){this.slPlayer=a},onPlayerStateChange:function(){this.playerState=this.getState();b(this.element).trigger("player_state_change",
this.playerState)},onMarkerReached:function(){},getState:function(){var a=this.getPlayerRef();try{if(this.options.mediaType=="flash")return a.State();if(this.options.mediaType=="html5")return this.getHtml5VideoState(a);if(this.options.mediaType=="win")return this.isWindowsMediaPlayer?["undefined","stopped","paused","playing","scanforward","scanreverse","buffering","waiting","mediaended","transitioning","ready","reconnecting"][a.playState]:["closed","opening","buffering","playing","paused","stopped",
"individualizing","acquiringlicense","clipplaying"][this.slPlayer.PlayState]}catch(f){return-1}},getHtml5VideoState:function(a){var f="undefined";if(a!=undefined)f="ready";if(a.paused&&this.html5VideoStarted&&!a.ended)return f="paused";if(!a.paused&&!a.ended&&a.currentTime>0){f="playing";this.html5VideoStarted=true;return f}if(a.currentTime>0){if(a.networkState==2)f="buffering";if(a.networkState==3)f="error - no source";if(a.ended)f="mediaended"}return f},getPlayerRef:function(){var a=b("#"+this.playerElementId);
return a.length?a[0]:null},show:function(){if(this.options.mediaType=="flash")if(b.browser.msie)this.beforeHideWidth!=undefined&&this.beforeHideHeight!=undefined?this.resize(this.beforeHideWidth,this.beforeHideHeight):this.resize(480,360);else this.element.css("left",0);this.options.mediaType=="html5"&&this.element.css("left",0);this.options.mediaType=="win"&&this.element.css("left",0);this.visible=true},hide:function(){if(this.options.mediaType=="flash")if(b.browser.msie){this.beforeHideWidth=this.width();
this.beforeHideHeight=this.height();this.resize(0,0)}else this.element.css("left",-2000);this.options.mediaType=="html5"&&this.element.css("left",-2000);this.options.mediaType=="win"&&this.element.css("left",-2000);this.visible=false},update:function(){},duration:function(){var a,f=this.getPlayerRef();if(this.options.mediaType=="flash")try{a=f.Duration()}catch(k){a=-1}if(this.options.mediaType=="html5")a=f.duration;if(this.options.mediaType=="win")a=this.currentPlayer=="silverlight"?this.slPlayer.EndPositionSeconds:
f.currentMedia.duration;return a},currentTime:function(a){var f=-1,k=this.getPlayerRef();if(a==undefined){if(this.options.mediaType=="flash")try{f=k.CurrentTime()}catch(w){f=-1}if(this.options.mediaType=="html5")f=k.currentTime;if(this.options.mediaType=="win")if(this.currentPlayer=="silverlight")f=this.slPlayer.PlaybackPositionSeconds;else if(k.controls!=undefined)f=k.controls.currentPosition}else{a=parseFloat(a);if(this.options.mediaType=="flash"){k.SetCurrentTime(a);f=k.CurrentTime()}if(this.options.mediaType==
"html5"){k.currentTime=a;f=k.currentTime}if(this.options.mediaType=="win")if(this.currentPlayer=="silverlight"){this.slPlayer.SeekToPosition(a);f=this.slPlayer.PlaybackPositionSeconds}else if(k.controls!=undefined){k.controls.currentPosition=a;f=k.controls.currentPosition}b(this.element).trigger("current_time_change",f)}return f},play:function(){var a=this.getPlayerRef();this.options.mediaType=="flash"&&a.Resume();this.options.mediaType=="html5"&&a.play();if(this.options.mediaType=="win")this.currentPlayer==
"silverlight"?this.slPlayer.Play():a.controls.play()},pause:function(){var a=this.getPlayerRef();this.options.mediaType=="flash"&&a.Pause();this.options.mediaType=="html5"&&a.pause();if(this.options.mediaType=="win")this.currentPlayer=="silverlight"?this.slPlayer.Pause():a.controls.pause()},stop:function(){var a=this.getPlayerRef();if(this.options.mediaType=="flash"){this.pause();this.currentTime(0)}if(this.options.mediaType=="html5"){a.pause();a.currentTime=0}if(this.options.mediaType=="win")this.currentPlayer==
"silverlight"?this.slPlayer.Stop():a.controls.stop()},volume:function(a){var f=this.getPlayerRef();if(a==undefined){if(this.options.mediaType=="flash")nReturn=f.Volume()*100;if(this.options.mediaType=="html5")nReturn=f.volume*100;if(this.options.mediaType=="win")if(this.currentPlayer=="silverlight")this.slPlayer.GetVolume();else nReturn=f.settings.volume}else{a=parseFloat(a);if(this.options.mediaType=="flash"){if(a>0)a/=100;f.SetVolume(a);nReturn=f.Volume()*100}if(this.options.mediaType=="html5"){if(a>
0)a/=100;f.volume=a;nReturn=f.volume*100}if(this.options.mediaType=="win")if(this.currentPlayer=="silverlight"){if(a>0)a/=100;this.slPlayer.SetVolume(a);nReturn=this.slPlayer.GetVolume()*100}else{f.settings.volume=a;nReturn=f.settings.volume}}return nReturn},resize:function(a,f){var k=this.find("#"+this.playerElementId);if(!(a==k.width()&&f==k.height())){if(this.options.mediaType=="win"&&!b.browser.msie&&this.currentPlayer!="silverlight"){if(this.currentTime()!=0&&this.currentTime()!=undefined)this.resizeTime=
this.currentTime();this.pause();this.options.width=a;this.options.height=f;this.element.html("");this.element.width(a);this.element.height(f);this.createMediaPlayer()}else{this.width(a);this.height(f)}this.element.trigger("media_resize")}},width:function(a){if(a==undefined)return this.element.width();else{this.element.width(a);b("#"+this.mediaContainerId).width(a);b("#"+this.playerElementId).width(a);return a}},height:function(a){if(a==undefined)return this.element.height();else{this.element.height(a);
b("#"+this.mediaContainerId).height(a);b("#"+this.playerElementId).height(a);return a}},loaded:function(){if(this.currentPlayer=="silverlight")if(this.slPlayer==undefined){util.log("Silverlight player not ready. Will retry after some time.");var a=this;setTimeout(function(){a.loaded()},500);return}util.log("Media Player Loaded event.");this.element.trigger("loaded")},stateChangeHandler:function(){this.onPlayerStateChange()}})});
function OnDSScriptCommandEvt(b,a){util.log("OnDSScriptCommandEvt");util.log("bstrType "+b+", bstrParam = "+a);if(a.indexOf("slidechanger.html?slide=")!=-1){var f=a.indexOf("=")+1,k=a.indexOf("&");f=a.substring(f,k);util.log("OnDSScriptCommandEvt SHOULD GO TO SLIDE "+f)}this.element.trigger("media_command",[b,a])}function OnDSPlayStateChangeEvt(b){util.log("OnDSPlayStateChangeEvt");util.log("OnDSPlayStateChangeEvt - state --\> "+b);$(".wmpControl").controller().onPlayerStateChange()}
function OnDSPositionChangeEvt(b,a){util.log("OnDSPositionChangeEvt");util.log("OnDSPositionChangeEvt - position old --\> "+b);util.log("OnDSPositionChangeEvt - position new --\> "+a)}function onPlayerReady(b){$(".silverlightControl").controller().setSilverlightPlayerRef(b);b.MarkerReached=onSLMarkerReached;b.PlayStateChanged=onSLPlayerStateChange}function onSLPlayerStateChange(b,a){$(".silverlightControl").controller().onPlayerStateChange()}
function handleFlashStreamCommand(b,a){if(source!="done"){sLog("loadHTML() - source = "+b);sLog("loadHTML() - frame = "+a)}}function handleFlashError(b){alert("An error has occurred with the Media Stream: \n\n"+b)}var myTempArgs,myTempSender;function onSLMarkerReached(b,a){myTempSender=b;myTempArgs=a;$(".silverlightControl").controller().mediaCommandHandler(a)}function flashStateChange(b,a){$("#"+a).controller().stateChangeHandler(b)}steal.loaded("nasdaq/media_player/media_player.js");
steal("jquery/class","jquery/lang/string","jquery/event/destroyed",function(b){var a=function(m,s,v){var F,B=m.bind&&m.unbind?m:b(w(m)?[m]:m);if(s.indexOf(">")===0){s=s.substr(1);F=function(L){L.target===m&&v.apply(this,arguments)}}B.bind(s,F||v);return function(){B.unbind(s,F||v);m=s=v=F=null}},f=b.makeArray,k=b.isArray,w=b.isFunction,E=b.extend,x=b.String,C=b.each,z=Array.prototype.slice,I=function(m,s,v,F){var B=m.delegate&&m.undelegate?m:b(w(m)?[m]:m);B.delegate(s,v,F);return function(){B.undelegate(s,
v,F);B=m=v=F=s=null}},n=function(m,s,v,F){return F?I(m,F,s,v):a(m,s,v)},h=function(m,s){var v=typeof s=="string"?m[s]:s;return function(){m.called=s;return v.apply(m,[this.nodeName?b(this):this].concat(z.call(arguments,0)))}},j=/\./g,d=/_?controllers?/ig,g=function(m){return x.underscore(m.replace("jQuery.","").replace(j,"_").replace(d,""))},p=/[^\w]/,u=/\{([^\}]+)\}/g,c=/^(?:(.*?)\s)?([\w\.\:>]+)$/,e,l=function(m,s){return b.data(m,"controllers",s)};b.Class("jQuery.Controller",{setup:function(){this._super.apply(this,
arguments);if(!(!this.shortName||this.fullName=="jQuery.Controller")){this._fullName=g(this.fullName);this._shortName=g(this.shortName);var m=this,s=this.pluginName||this._fullName,v;b.fn[s]||(b.fn[s]=function(F){var B=f(arguments),L=typeof F=="string"&&w(m.prototype[F]),X=B[0];return this.each(function(){var O=l(this);if(O=O&&O[s])L?O[X].apply(O,B.slice(1)):O.update.apply(O,B);else m.newInstance.apply(m,[this].concat(B))})});if(!k(this.listensTo))throw"listensTo is not an array in "+this.fullName;
this.actions={};for(v in this.prototype)if(!(v=="constructor"||!w(this.prototype[v])))if(this._isAction(v))this.actions[v]=this._action(v)}},hookup:function(m){return new this(m)},_isAction:function(m){return p.test(m)?true:b.inArray(m,this.listensTo)>-1||b.event.special[m]||t[m]},_action:function(m,s){u.lastIndex=0;if(!s&&u.test(m))return null;m=s?x.sub(m,[s,window]):m;s=k(m);var v=(s?m[1]:m).match(c);return{processor:t[v[2]]||e,parts:v,delegate:s?m[0]:undefined}},processors:{},listensTo:[],defaults:{}},
{setup:function(m,s){var v=this.constructor;m=m.jquery?m[0]:m;var F=v.pluginName||v._fullName;this.element=b(m).addClass(F);(l(m)||l(m,{}))[F]=this;this.options=E(E(true,{},v.defaults),s);this.called="init";this.bind();return this.element},bind:function(m,s,v){if(m===undefined){this._bindings=[];m=this.constructor;s=this._bindings;v=m.actions;var F=this.element;for(funcName in v)if(v.hasOwnProperty(funcName)){ready=v[funcName]||m._action(funcName,this.options);s.push(ready.processor(ready.delegate||
F,ready.parts[2],ready.parts[1],funcName,this))}var B=h(this,"destroy");F.bind("destroyed",B);s.push(function(L){b(L).unbind("destroyed",B)});return s.length}if(typeof m=="string"){v=s;s=m;m=this.element}return this._binder(m,s,v)},_binder:function(m,s,v,F){if(typeof v=="string")v=h(this,v);this._bindings.push(n(m,s,v,F));return this._bindings.length},_unbind:function(){var m=this.element[0];C(this._bindings,function(s,v){v(m)});this._bindings=[]},delegate:function(m,s,v,F){if(typeof m=="string"){F=
v;v=s;s=m;m=this.element}return this._binder(m,v,F,s)},update:function(m){E(this.options,m);this._unbind();this.bind()},destroy:function(){if(this._destroyed)throw this.constructor.shortName+" controller already deleted";var m=this.constructor.pluginName||this.constructor._fullName;this._destroyed=true;this.element.removeClass(m);this._unbind();delete this._actions;delete this.element.data("controllers")[m];b(this).triggerHandler("destroyed");this.element=null},find:function(m){return this.element.find(m)},
_set_called:true});var t=b.Controller.processors;e=function(m,s,v,F,B){return n(m,s,h(B,F),v)};C("change click contextmenu dblclick keydown keyup keypress mousedown mousemove mouseout mouseover mouseup reset resize scroll select submit focusin focusout mouseenter mouseleave".split(" "),function(m,s){t[s]=e});var y,r=function(m,s){for(y=0;y<s.length;y++)if(typeof s[y]=="string"?m.constructor._shortName==s[y]:m instanceof s[y])return true;return false};b.fn.extend({controllers:function(){var m=f(arguments),
s=[],v,F,B;this.each(function(){v=b.data(this,"controllers");for(B in v)if(v.hasOwnProperty(B)){F=v[B];if(!m.length||r(F,m))s.push(F)}});return s},controller:function(){return this.controllers.apply(this,arguments)[0]}})});steal.loaded("jquery/controller/controller.js");
steal("jquery/view","jquery/lang/string/rsplit").then(function(b){var a=function(d){eval(d)},f=function(d){return d.substr(0,d.length-1)},k=b.String.rsplit,w=b.extend,E=b.isArray,x=function(d){return d.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/"/g,'\\"').replace(/\t/g,"\\t")},C=function(d){return d.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&#34;").replace(/'/g,"&#39;")},z=function(d){if(this.constructor!=z){var g=new z(d);return function(p,u){return g.render(p,
u)}}if(typeof d=="function"){this.template={};this.template.process=d}else{w(this,z.options,d);this.template=j(this.text,this.type,this.name)}};b.EJS=z;z.prototype={constructor:z,render:function(d,g){d=d||{};this._extra_helpers=g;g=new z.Helpers(d,g||{});return this.template.process.call(d,d,g)}};z.text=function(d){if(typeof d=="string")return d;if(d===null||d===undefined)return"";var g=d.hookup&&function(p,u){d.hookup.call(d,p,u)}||typeof d=="function"&&d||E(d)&&function(p,u){for(var c=0;c<d.length;c++)d[c].hookup?
d[c].hookup(p,u):d[c](p,u)};if(g)return"data-view-id='"+b.View.hookup(g)+"'";return d.toString?d.toString():""};z.clean=function(d){return typeof d=="string"?C(d):typeof d=="number"?d:z.text(d)};var I=function(d,g,p){g=k(g,/\n/);for(var u=0;u<g.length;u++)n(d,g[u],p)},n=function(d,g,p){d.lines++;g=k(g,d.splitter);for(var u,c=0;c<g.length;c++){u=g[c];u!==null&&p(u,d)}},h=function(d,g){var p={};w(p,{left:d+"%",right:"%"+g,dLeft:d+"%%",dRight:"%%"+g,eeLeft:d+"%==",eLeft:d+"%=",cmnt:d+"%#",scan:I,lines:0});
p.splitter=new RegExp("("+[p.dLeft,p.dRight,p.eeLeft,p.eLeft,p.cmnt,p.left,p.right+"\n",p.right,"\n"].join(")|(").replace(/\[/g,"\\[").replace(/\]/g,"\\]")+")");return p},j=function(d,g,p){d=d.replace(/\r\n/g,"\n").replace(/\r/g,"\n");g=g||"<";var u=new z.Buffer(["var ___v1ew = [];"],[]),c="",e=function(y){u.push("___v1ew.push(",'"',x(y),'");')},l=null,t=function(){c=""};I(h(g,g==="["?"]":">"),d||"",function(y,r){if(l===null)switch(y){case "\n":c+="\n";e(c);u.cr();t();break;case r.left:case r.eLeft:case r.eeLeft:case r.cmnt:l=
y;c.length>0&&e(c);t();break;case r.dLeft:c+=r.left;break;default:c+=y;break}else switch(y){case r.right:switch(l){case r.left:if(c[c.length-1]=="\n"){c=f(c);u.push(c,";");u.cr()}else u.push(c,";");break;case r.eLeft:u.push("___v1ew.push(","(jQuery.EJS.clean(",c,")));");break;case r.eeLeft:u.push("___v1ew.push(","(jQuery.EJS.text(",c,")));");break}l=null;t();break;case r.dRight:c+=r.right;break;default:c+=y;break}});c.length>0&&u.push("___v1ew.push(",'"',x(c)+'");');d={out:"try { with(_VIEW) { with (_CONTEXT) {"+
u.close()+" return ___v1ew.join('');}}}catch(e){e.lineNumber=null;throw e;}"};a.call(d,"this.process = (function(_CONTEXT,_VIEW){"+d.out+"});\r\n//@ sourceURL="+p+".js");return d};z.Buffer=function(d,g){this.line=[];this.script=[];this.post=g;this.push.apply(this,d)};z.Buffer.prototype={push:function(){this.line.push.apply(this.line,arguments)},cr:function(){this.script.push(this.line.join(""),"\n");this.line=[]},close:function(){if(this.line.length>0){this.script.push(this.line.join(""));this.line=
[]}this.post.length&&this.push.apply(this,this.post);this.script.push(";");return this.script.join("")}};z.options={type:"<",ext:".ejs"};z.Helpers=function(d,g){this._data=d;this._extras=g;w(this,g)};z.Helpers.prototype={plugin:function(){var d=b.makeArray(arguments),g=d.shift();return function(p){p=b(p);p[g].apply(p,d)}},view:function(d,g,p){p=p||this._extras;g=g||this._data;return b.View(d,g,p)}};b.View.register({suffix:"ejs",script:function(d,g){return"jQuery.EJS(function(_CONTEXT,_VIEW) { "+(new z({text:g,
name:d})).template.out+" })"},renderer:function(d,g){var p=new z({text:g,name:d});return function(u,c){return p.render.call(p,u,c)}}})});steal.loaded("jquery/view/ejs/ejs.js");
steal("jquery/controller","jquery/view").then(function(){jQuery.Controller.getFolder=function(){return jQuery.String.underscore(this.fullName.replace(/\./g,"/")).replace("/Controllers","")};jQuery.Controller._calculatePosition=function(a,f,k){var w=a.fullName.split("."),E=w.slice(0);E.splice(0,2);E.join("/");w=(a=w.length>2&&w[1]=="Controllers")?jQuery.String.underscore(w[0]):jQuery.String.underscore(w.join("/"));E=jQuery.String.underscore(E.join("/")).toLowerCase();var x=typeof f=="string"&&/\.[\w\d]+$/.test(f)?
"":jQuery.View.ext;if(typeof f=="string"){if(f.substr(0,2)!="//")f="//"+(new steal.File("views/"+(f.indexOf("/")!==-1?f:(a?E+"/":"")+f))).joinFrom(w)+x}else f||(f="//"+(new steal.File("views/"+(a?E+"/":"")+k.replace(/\.|#/g,"").replace(/ /g,"_"))).joinFrom(w)+x);return f};var b=function(a){var f={};if(a)if(jQuery.isArray(a))for(var k=0;k<a.length;k++)jQuery.extend(f,a[k]);else jQuery.extend(f,a);else{if(this._default_helpers)f=this._default_helpers;a=window;k=this.constructor.fullName.split(/\./);
for(var w=0;w<k.length;w++){typeof a.Helpers=="object"&&jQuery.extend(f,a.Helpers);a=a[k[w]]}typeof a.Helpers=="object"&&jQuery.extend(f,a.Helpers);this._default_helpers=f}return f};jQuery.Controller.prototype.view=function(a,f,k){if(typeof a!="string"&&!k){k=f;f=a;a=null}a=jQuery.Controller._calculatePosition(this.Class,a,this.called);f=f||this;k=b.call(this,k);return jQuery.View(a,f,k)}});steal.loaded("jquery/controller/view/view.js");
steal("jquery/class","jquery/lang/string",function(){var b=$.String.underscore,a=$.String.classize,f=$.isArray,k=$.makeArray,w=$.extend,E=$.each,x=/GET|POST|PUT|DELETE/i,C=function(c,e,l,t,y,r,m){m=m||"json";var s="";if(typeof c=="string"){var v=c.indexOf(" ");if(v>2&&v<7){s=c.substr(0,v);if(x.test(s))r=s;else m=s;s=c.substr(v+1)}else s=c}typeof e=="object"&&!f(e)&&(e=w({},e));c=$.String.sub(s,e,true);return $.ajax({url:c,data:e,success:l,error:t,type:r||"post",dataType:m,fixture:y})},z=function(c,
e){var l=b(this.shortName),t="-"+l+(c||"");return $.fixture&&$.fixture[t]?t:e||"//"+b(this.fullName).replace(/\.models\..*/,"").replace(/\./g,"/")+"/fixtures/"+l+(c||"")+".json"},I=function(c,e){c=c||{};var l=this.id;if(c[l]&&c[l]!==e){c["new"+$.String.capitalize(e)]=c[l];delete c[l]}c[l]=e;return c},n=function(c){return new (c||$.Model.List||Array)},h=function(c){return c[c.constructor.id]},j=function(c){for(var e=[],l=0;l<c.length;l++)if(!c[l]["__u Nique"]){e.push(c[l]);c[l]["__u Nique"]=true}for(l=
0;l<e.length;l++)delete e[l]["__u Nique"];return e},d=function(c,e,l,t,y){var r=$.Deferred(),m=[c.serialize(),function(v){c[y||e+"d"](v);r.resolveWith(c,[c,v,e])},function(v){r.rejectWith(c,[v])}],s=c.constructor;e=="destroy"&&m.shift();e!=="create"&&m.unshift(h(c));r.then(l);r.fail(t);s[e].apply(s,m);return r.promise()},g=function(c){return typeof c==="object"&&c!==null&&c},p=function(c){return function(){$.fn[c].apply($([this]),arguments);return this}},u=p("bind");p=p("unbind");ajaxMethods={create:function(c){return function(e,
l,t){return C(c,e,l,t,z.call(this,"Create","-restCreate"))}},update:function(c){return function(e,l,t,y){return C(c,I.call(this,l,e),t,y,z.call(this,"Update","-restUpdate"),"put")}},destroy:function(c){return function(e,l,t){var y={};y[this.id]=e;return C(c,y,l,t,z.call(this,"Destroy","-restDestroy"),"delete")}},findAll:function(c){return function(e,l,t){return C(c||this.shortName+"s.json",e,l,t,z.call(this,"s"),"get","json "+this._shortName+".models")}},findOne:function(c){return function(e,l,t){return C(c,
e,l,t,z.call(this),"get","json "+this._shortName+".model")}}};jQuery.Class("jQuery.Model",{setup:function(c){var e=this;E(["attributes","associations","validations"],function(y,r){if(!e[r]||c[r]===e[r])e[r]={}});E(["convert","serialize"],function(y,r){if(c[r]!=e[r])e[r]=w({},c[r],e[r])});this._fullName=b(this.fullName.replace(/\./g,"_"));this._shortName=b(this.shortName);if(this.fullName.substr(0,7)!="jQuery."){if(this.listType)this.list=new this.listType([]);for(var l in ajaxMethods)if(typeof this[l]!==
"function")this[l]=ajaxMethods[l](this[l]);l={};var t="* "+this._shortName+".model";l[t+"s"]=this.proxy("models");l[t]=this.proxy("model");$.ajaxSetup({converters:l})}},attributes:{},model:function(c){if(!c)return null;if(c instanceof this)c=c.serialize();return new this(g(c[this._shortName])||g(c.data)||g(c.attributes)||c)},models:function(c){if(!c)return null;var e=n(this.List),l=f(c),t=$.Model.List&&c instanceof $.Model.List;t=l?c:t?c.serialize():c.data;var y=t.length,r=0;for(e._use_call=true;r<
y;r++)e.push(this.model(t[r]));if(!l)for(var m in c)if(m!=="data")e[m]=c[m];return e},id:"id",addAttr:function(c,e){if(!this.associations[c]){this.attributes[c]||(this.attributes[c]=e);return e}},_models:{},publish:function(c,e){window.OpenAjax&&OpenAjax.hub.publish(this._shortName+"."+c,e)},guessType:function(){return"string"},convert:{date:function(c){var e=typeof c;return e==="string"?isNaN(Date.parse(c))?null:Date.parse(c):e==="number"?new Date(c):c},number:function(c){return parseFloat(c)},"boolean":function(c){return Boolean(c)},
"default":function(c,e,l){e=$.String.getObject(l);var t=window;if(l.indexOf(".")>=0){l=l.substring(0,l.lastIndexOf("."));t=$.String.getObject(l)}return typeof e=="function"?e.call(t,c):c}},serialize:{"default":function(c){return g(c)&&c.serialize?c.serialize():c}},bind:u,unbind:p,_ajax:C},{setup:function(c){this._init=true;this.attrs(w({},this.constructor.defaults,c));delete this._init},update:function(c,e,l){this.attrs(c);return this.save(e,l)},errors:function(c){if(c)c=f(c)?c:k(arguments);var e=
{},l=this,t=function(m,s){E(s,function(v,F){if(v=F.call(l)){e.hasOwnProperty(m)||(e[m]=[]);e[m].push(v)}})},y=this.constructor.validations;E(c||y||{},function(m,s){if(typeof m=="number"){m=s;s=y[m]}t(m,s||[])});for(var r in e)if(e.hasOwnProperty(r))return e;return null},attr:function(c,e,l,t){var y=a(c),r="get"+y;if(e!==undefined){this._setProperty(c,e,l,t,y);return this}return this[r]?this[r]():this[c]},bind:u,unbind:p,_setProperty:function(c,e,l,t,y){y="set"+y;var r=this[c],m=this,s=function(v){t&&
t.call(m,v);$(m).triggerHandler("error."+c,v)};this[y]&&(e=this[y](e,this.proxy("_updateProperty",c,e,r,l,s),s))===undefined||this._updateProperty(c,e,r,l,s)},_updateProperty:function(c,e,l,t,y){var r=this.constructor,m=r.attributes[c]||r.addAttr(c,r.guessType(e)),s=r.convert[m]||r.convert["default"],v=null,F="",B="updated.";t=t;var L=r.list;e=this[c]=e===null?null:s.call(r,e,function(){},m);this._init||(v=this.errors(c));m=[e];s=[c,e,l];if(v){F=B="error.";t=y;s.splice(1,0,v);m.unshift(v)}if(l!==
e&&!this._init){!v&&$(this).triggerHandler(F+c,m);$(this).triggerHandler(B+"attr",s)}t&&t.apply(this,m);if(c===r.id&&e!==null&&L)if(l){if(l!=e){L.remove(l);L.push(this)}}else L.push(this)},removeAttr:function(c){var e=this[c],l=false,t=this.constructor.attributes;this[c]&&delete this[c];if(t[c]){delete t[c];l=true}!this._init&&l&&e&&$(this).triggerHandler("updated.attr",[c,null,e])},attrs:function(c){var e,l=this.constructor,t=l.attributes;if(c){l=l.id;for(e in c)e!=l&&this.attr(e,c[e]);l in c&&this.attr(l,
c[l])}else{c={};for(e in t)if(t.hasOwnProperty(e))c[e]=this.attr(e)}return c},serialize:function(){var c=this.constructor,e=c.attributes,l,t,y={},r;attributes={};for(r in e)if(e.hasOwnProperty(r)){l=e[r];t=c.serialize[l]||c.serialize["default"];y[r]=t(this[r],l)}return y},isNew:function(){var c=h(this);return c===undefined||c===null},save:function(c,e){return d(this,this.isNew()?"create":"update",c,e)},destroy:function(c,e){return d(this,"destroy",c,e,"destroyed")},identity:function(){var c=h(this),
e=this.constructor;return(e._fullName+"_"+(e.escapeIdentity?encodeURIComponent(c):c)).replace(/ /g,"_")},elements:function(c){return $("."+this.identity(),c)},publish:function(c,e){this.constructor.publish(c,e||this)},hookup:function(c){var e=this.constructor._shortName,l=$.data(c,"models")||$.data(c,"models",{});$(c).addClass(e+" "+this.identity());l[e]=this}});E(["created","updated","destroyed"],function(c,e){$.Model.prototype[e]=function(l){var t=this.constructor;e==="destroyed"&&t.list&&t.list.remove(h(this));
l&&typeof l=="object"&&this.attrs(l.attrs?l.attrs():l);$(this).triggerHandler(e);this.publish(e,this);$([t]).triggerHandler(e,this);return[this].concat(k(arguments))}});$.fn.models=function(){var c=[],e,l;this.each(function(){E($.data(this,"models")||{},function(t,y){e=e===undefined?y.constructor.List||null:y.constructor.List===e?e:null;c.push(y)})});l=n(e);l.push.apply(l,j(c));return l};$.fn.model=function(c){if(c&&c instanceof $.Model){c.hookup(this[0]);return this}else return this.models.apply(this,
arguments)[0]}});steal.loaded("jquery/model/model.js");var util;
steal(/* "jquery").then( */ "lib/jquery-jqplugin",function(b){util={supports_video:function(){return!!document.createElement("video").canPlayType},supports_h264_baseline_video:function(){if(!util.supports_video())return false;return document.createElement("video").canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"')},supports_ogg_theora_video:function(){if(!util.supports_video())return false;return document.createElement("video").canPlayType('video/ogg; codecs="theora, vorbis"')},supports_webm_video:function(){if(!util.supports_video())return false;
return document.createElement("video").canPlayType('video/webm; codecs="vp8, vorbis"')},supports_flash:function(){return b.browser.flash},supports_win:function(){return b.browser.wmp},supports_silverlight:function(){return b.browser.sl},isIphone:function(){return navigator.userAgent.toLowerCase().indexOf("iphone")==-1?false:true},isIpad:function(){return navigator.userAgent.toLowerCase().indexOf("ipad")==-1?false:true},isIpod:function(){return navigator.userAgent.toLowerCase().indexOf("ipod")==-1?
false:true},isIosDevice:function(){var a=false;if(this.isIphone()||this.isIpad()||this.isIpod())a=true;return a},formatSecondsToTime:function(a){var f="";f=parseInt(a/3600)%24;var k=parseInt(a/60)%60;a=parseInt(a%60);return f=(f<10?"0"+f:f)+":"+(k<10?"0"+k:k)+":"+(a<10?"0"+a:a)},getPagePath:function(a){var f=window.location.protocol+"//"+window.location.host+window.location.pathname;if(a==false)f=f.match(/^(http.+\/)[^\/]+$/)[1];return f},getHost:function(){var a=location.protocol+"//"+location.hostname;
a+=location.port.length>0?":"+location.port+"/":"/";return a},log:function(a){try{console.log(a)}catch(f){}},logerror:function(a){try{console.log("Error: "+a)}catch(f){}},replaceTokens:function(a,f){return a.replace(/\{(.+?)\}/g,function(k){return f[k]})},getScheme:function(a){var f=a.indexOf(":");if(f>5)throw"Url doesnt have proper scheme specified.";a=a.substring(0,f).toLowerCase();if(a=="http"||a=="https")return a;throw"Url doesnt have proper scheme specified.";},friendlyDate:function(a){a=Date.parse(a);
return a.getMonthName()+" "+a.getDate()+", "+a.getFullYear()},generateUniqueId:function(a,f){for(var k="",w=0;w<a;w++)k+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(Math.random()*62));if(f!=undefined)k=f+k;return k}}});steal.loaded("lib/utilities/utilities.js");if(!window.Silverlight)window.Silverlight={};Silverlight._silverlightCount=0;Silverlight.__onSilverlightInstalledCalled=false;Silverlight.fwlinkRoot="http://go2.microsoft.com/fwlink/?LinkID=";
Silverlight.__installationEventFired=false;Silverlight.onGetSilverlight=null;Silverlight.onSilverlightInstalled=function(){window.location.reload(false)};
Silverlight.isInstalled=function(b){if(b==undefined)b=null;var a=false;try{var f=null,k=false;if(window.ActiveXObject)try{f=new ActiveXObject("AgControl.AgControl");if(b===null)a=true;else if(f.IsVersionSupported(b))a=true}catch(w){k=true}else k=true;if(k){var E=navigator.plugins["Silverlight Plug-In"];if(E)if(b===null)a=true;else{var x=E.description;if(x==="1.0.30226.2")x="2.0.30226.2";for(var C=x.split(".");C.length>3;)C.pop();for(;C.length<4;)C.push(0);for(var z=b.split(".");z.length>4;)z.pop();
var I,n;b=0;do{I=parseInt(z[b]);n=parseInt(C[b]);b++}while(b<z.length&&I===n);if(I<=n&&!isNaN(I))a=true}}}catch(h){a=false}return a};
Silverlight.WaitForInstallCompletion=function(){if(!Silverlight.isBrowserRestartRequired&&Silverlight.onSilverlightInstalled){try{navigator.plugins.refresh()}catch(b){}if(Silverlight.isInstalled(null)&&!Silverlight.__onSilverlightInstalledCalled){Silverlight.onSilverlightInstalled();Silverlight.__onSilverlightInstalledCalled=true}else setTimeout(Silverlight.WaitForInstallCompletion,3E3)}};
Silverlight.__startup=function(){navigator.plugins.refresh();Silverlight.isBrowserRestartRequired=Silverlight.isInstalled(null);if(Silverlight.isBrowserRestartRequired){if(window.navigator.mimeTypes){var b=navigator.mimeTypes["application/x-silverlight-2"],a=navigator.mimeTypes["application/x-silverlight-2-b2"],f=navigator.mimeTypes["application/x-silverlight-2-b1"],k=f;if(a)k=a;if(!b&&(f||a)){if(!Silverlight.__installationEventFired){Silverlight.onUpgradeRequired();Silverlight.__installationEventFired=
true}}else if(b&&k)if(b.enabledPlugin&&k.enabledPlugin)if(b.enabledPlugin.description!=k.enabledPlugin.description)if(!Silverlight.__installationEventFired){Silverlight.onRestartRequired();Silverlight.__installationEventFired=true}}}else{Silverlight.WaitForInstallCompletion();if(!Silverlight.__installationEventFired){Silverlight.onInstallRequired();Silverlight.__installationEventFired=true}}Silverlight.disableAutoStartup||(window.removeEventListener?window.removeEventListener("load",Silverlight.__startup,
false):window.detachEvent("onload",Silverlight.__startup))};Silverlight.disableAutoStartup||(window.addEventListener?window.addEventListener("load",Silverlight.__startup,false):window.attachEvent("onload",Silverlight.__startup));
Silverlight.createObject=function(b,a,f,k,w,E,x){var C={};C.version=k.version;k.source=b;C.alt=k.alt;if(E)k.initParams=E;if(k.isWindowless&&!k.windowless)k.windowless=k.isWindowless;if(k.framerate&&!k.maxFramerate)k.maxFramerate=k.framerate;if(f&&!k.id)k.id=f;delete k.ignoreBrowserVer;delete k.inplaceInstallPrompt;delete k.version;delete k.isWindowless;delete k.framerate;delete k.data;delete k.src;delete k.alt;if(Silverlight.isInstalled(C.version)){for(var z in w)if(w[z]){if(z=="onLoad"&&typeof w[z]==
"function"&&w[z].length!=1){var I=w[z];w[z]=function(n){return I(document.getElementById(f),x,n)}}b=Silverlight.__getHandlerName(w[z]);if(b!=null){k[z]=b;w[z]=null}else throw"typeof events."+z+" must be 'function' or 'string'";}slPluginHTML=Silverlight.buildHTML(k)}else slPluginHTML=Silverlight.buildPromptHTML(C);if(a)a.innerHTML=slPluginHTML;else return slPluginHTML};
Silverlight.buildHTML=function(b){var a=[];a.push('<object type="application/x-silverlight" data="data:application/x-silverlight,"');b.id!=null&&a.push(' id="'+Silverlight.HtmlAttributeEncode(b.id)+'"');b.width!=null&&a.push(' width="'+b.width+'"');b.height!=null&&a.push(' height="'+b.height+'"');a.push(" >");delete b.id;delete b.width;delete b.height;for(var f in b)b[f]&&a.push('<param name="'+Silverlight.HtmlAttributeEncode(f)+'" value="'+Silverlight.HtmlAttributeEncode(b[f])+'" />');a.push("</object>");
return a.join("")};Silverlight.createObjectEx=function(b){var a=Silverlight.createObject(b.source,b.parentElement,b.id,b.properties,b.events,b.initParams,b.context);if(b.parentElement==null)return a};
Silverlight.buildPromptHTML=function(b){var a="",f=Silverlight.fwlinkRoot,k=b.version;if(b.alt)a=b.alt;else{k||(k="");a="<a href='javascript:Silverlight.getSilverlight(\"{1}\");' style='text-decoration: none;'><img src='{2}' alt='Get Microsoft Silverlight' style='border-style: none'/></a>";a=a.replace("{1}",k);a=a.replace("{2}",f+"108181")}return a};
Silverlight.getSilverlight=function(b){Silverlight.onGetSilverlight&&Silverlight.onGetSilverlight();var a="";b=String(b).split(".");if(b.length>1){a=parseInt(b[0]);a=isNaN(a)||a<2?"1.0":b[0]+"."+b[1]}b="";if(a.match(/^\d+\056\d+$/))b="&v="+a;Silverlight.followFWLink("149156"+b)};Silverlight.followFWLink=function(b){top.location=Silverlight.fwlinkRoot+String(b)};
Silverlight.HtmlAttributeEncode=function(b){var a,f="";if(b==null)return null;for(var k=0;k<b.length;k++){a=b.charCodeAt(k);if(a>96&&a<123||a>64&&a<91||a>43&&a<58&&a!=47||a==95)f+=String.fromCharCode(a);else f=f+"&#"+a+";"}return f};
Silverlight.default_error_handler=function(b,a){b=a.ErrorType;var f="\nSilverlight error message     \n";f+="ErrorCode: "+a.ErrorCode+"\n";f+="ErrorType: "+b+"       \n";f+="Message: "+a.ErrorMessage+"     \n";if(b=="ParserError"){f+="XamlFile: "+a.xamlFile+"     \n";f+="Line: "+a.lineNumber+"     \n";f+="Position: "+a.charPosition+"     \n"}else if(b=="RuntimeError"){if(a.lineNumber!=0){f+="Line: "+a.lineNumber+"     \n";f+="Position: "+a.charPosition+"     \n"}f+="MethodName: "+a.methodName+"     \n"}alert(f)};
Silverlight.__cleanup=function(){for(var b=Silverlight._silverlightCount-1;b>=0;b--)window["__slEvent"+b]=null;Silverlight._silverlightCount=0;window.removeEventListener?window.removeEventListener("unload",Silverlight.__cleanup,false):window.detachEvent("onunload",Silverlight.__cleanup)};
Silverlight.__getHandlerName=function(b){var a="";if(typeof b=="string")a=b;else if(typeof b=="function"){if(Silverlight._silverlightCount==0)window.addEventListener?window.addEventListener("onunload",Silverlight.__cleanup,false):window.attachEvent("onunload",Silverlight.__cleanup);a="__slEvent"+Silverlight._silverlightCount++;window[a]=b}else a=null;return a};Silverlight.onRequiredVersionAvailable=function(){};Silverlight.onRestartRequired=function(){};Silverlight.onUpgradeRequired=function(){};
Silverlight.onInstallRequired=function(){};
Silverlight.IsVersionAvailableOnError=function(b,a){b=false;try{if(a.ErrorCode==8001&&!Silverlight.__installationEventFired){Silverlight.onUpgradeRequired();Silverlight.__installationEventFired=true}else if(a.ErrorCode==8002&&!Silverlight.__installationEventFired){Silverlight.onRestartRequired();Silverlight.__installationEventFired=true}else if(a.ErrorCode==5014||a.ErrorCode==2106){if(Silverlight.__verifySilverlight2UpgradeSuccess(a.getHost()))b=true}else b=true}catch(f){}return b};
Silverlight.IsVersionAvailableOnLoad=function(b){var a=false;try{if(Silverlight.__verifySilverlight2UpgradeSuccess(b.getHost()))a=true}catch(f){}return a};
Silverlight.__verifySilverlight2UpgradeSuccess=function(b){var a=false,f=null;try{if(b.IsVersionSupported("2.0.31005.99")){f=Silverlight.onRequiredVersionAvailable;a=true}else f=b.IsVersionSupported("2.0.31005.0")?Silverlight.onRestartRequired:Silverlight.onUpgradeRequired;if(f&&!Silverlight.__installationEventFired){f();Silverlight.__installationEventFired=true}}catch(k){}return a};steal.loaded("lib/microsoft-playerframework/silverlight.js");
var swfobject=function(){function b(){if(!T){try{var o=B.getElementsByTagName("body")[0].appendChild(u("span"));o.parentNode.removeChild(o)}catch(q){return}T=true;o=O.length;for(var A=0;A<o;A++)O[A]()}}function a(o){if(T)o();else O[O.length]=o}function f(o){if(typeof F.addEventListener!=r)F.addEventListener("load",o,false);else if(typeof B.addEventListener!=r)B.addEventListener("load",o,false);else if(typeof F.attachEvent!=r)c(F,"onload",o);else if(typeof F.onload=="function"){var q=F.onload;F.onload=
function(){q();o()}}else F.onload=o}function k(){X?w():E()}function w(){var o=B.getElementsByTagName("body")[0],q=u(m);q.setAttribute("type",s);var A=o.appendChild(q);if(A){var D=0;(function(){if(typeof A.GetVariable!=r){var G=A.GetVariable("$version");if(G){G=G.split(" ")[1].split(",");H.pv=[parseInt(G[0],10),parseInt(G[1],10),parseInt(G[2],10)]}}else if(D<10){D++;setTimeout(arguments.callee,10);return}o.removeChild(q);A=null;E()})()}else E()}function E(){var o=R.length;if(o>0)for(var q=0;q<o;q++){var A=
R[q].id,D=R[q].callbackFn,G={success:false,id:A};if(H.pv[0]>0){var J=p(A);if(J)if(e(R[q].swfVersion)&&!(H.wk&&H.wk<312)){t(A,true);if(D){G.success=true;G.ref=x(A);D(G)}}else if(R[q].expressInstall&&C()){G={};G.data=R[q].expressInstall;G.width=J.getAttribute("width")||"0";G.height=J.getAttribute("height")||"0";if(J.getAttribute("class"))G.styleclass=J.getAttribute("class");if(J.getAttribute("align"))G.align=J.getAttribute("align");var K={};J=J.getElementsByTagName("param");for(var M=J.length,N=0;N<
M;N++)if(J[N].getAttribute("name").toLowerCase()!="movie")K[J[N].getAttribute("name")]=J[N].getAttribute("value");z(G,K,A,D)}else{I(J);D&&D(G)}}else{t(A,true);if(D){if((A=x(A))&&typeof A.SetVariable!=r){G.success=true;G.ref=A}D(G)}}}}function x(o){var q=null;if((o=p(o))&&o.nodeName=="OBJECT")if(typeof o.SetVariable!=r)q=o;else if(o=o.getElementsByTagName(m)[0])q=o;return q}function C(){return!Y&&e("6.0.65")&&(H.win||H.mac)&&!(H.wk&&H.wk<312)}function z(o,q,A,D){Y=true;ea=D||null;ga={success:false,
id:A};var G=p(A);if(G){if(G.nodeName=="OBJECT"){V=n(G);Z=null}else{V=G;Z=A}o.id=v;if(typeof o.width==r||!/%$/.test(o.width)&&parseInt(o.width,10)<310)o.width="310";if(typeof o.height==r||!/%$/.test(o.height)&&parseInt(o.height,10)<137)o.height="137";B.title=B.title.slice(0,47)+" - Flash Player Installation";D=H.ie&&H.win?"ActiveX":"PlugIn";D="MMredirectURL="+F.location.toString().replace(/&/g,"%26")+"&MMplayerType="+D+"&MMdoctitle="+B.title;if(typeof q.flashvars!=r)q.flashvars+="&"+D;else q.flashvars=
D;if(H.ie&&H.win&&G.readyState!=4){D=u("div");A+="SWFObjectNew";D.setAttribute("id",A);G.parentNode.insertBefore(D,G);G.style.display="none";(function(){G.readyState==4?G.parentNode.removeChild(G):setTimeout(arguments.callee,10)})()}h(o,q,A)}}function I(o){if(H.ie&&H.win&&o.readyState!=4){var q=u("div");o.parentNode.insertBefore(q,o);q.parentNode.replaceChild(n(o),q);o.style.display="none";(function(){o.readyState==4?o.parentNode.removeChild(o):setTimeout(arguments.callee,10)})()}else o.parentNode.replaceChild(n(o),
o)}function n(o){var q=u("div");if(H.win&&H.ie)q.innerHTML=o.innerHTML;else if(o=o.getElementsByTagName(m)[0])if(o=o.childNodes)for(var A=o.length,D=0;D<A;D++)!(o[D].nodeType==1&&o[D].nodeName=="PARAM")&&o[D].nodeType!=8&&q.appendChild(o[D].cloneNode(true));return q}function h(o,q,A){var D,G=p(A);if(H.wk&&H.wk<312)return D;if(G){if(typeof o.id==r)o.id=A;if(H.ie&&H.win){var J="";for(var K in o)if(o[K]!=Object.prototype[K])if(K.toLowerCase()=="data")q.movie=o[K];else if(K.toLowerCase()=="styleclass")J+=
' class="'+o[K]+'"';else if(K.toLowerCase()!="classid")J+=" "+K+'="'+o[K]+'"';K="";for(var M in q)if(q[M]!=Object.prototype[M])K+='<param name="'+M+'" value="'+q[M]+'" />';G.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+J+">"+K+"</object>";aa[aa.length]=o.id;D=p(o.id)}else{M=u(m);M.setAttribute("type",s);for(J in o)if(o[J]!=Object.prototype[J])if(J.toLowerCase()=="styleclass")M.setAttribute("class",o[J]);else J.toLowerCase()!="classid"&&M.setAttribute(J,o[J]);for(var N in q)q[N]!=
Object.prototype[N]&&N.toLowerCase()!="movie"&&j(M,N,q[N]);G.parentNode.replaceChild(M,G);D=M}}return D}function j(o,q,A){var D=u("param");D.setAttribute("name",q);D.setAttribute("value",A);o.appendChild(D)}function d(o){var q=p(o);if(q&&q.nodeName=="OBJECT")if(H.ie&&H.win){q.style.display="none";(function(){q.readyState==4?g(o):setTimeout(arguments.callee,10)})()}else q.parentNode.removeChild(q)}function g(o){if(o=p(o)){for(var q in o)if(typeof o[q]=="function")o[q]=null;o.parentNode.removeChild(o)}}
function p(o){var q=null;try{q=B.getElementById(o)}catch(A){}return q}function u(o){return B.createElement(o)}function c(o,q,A){o.attachEvent(q,A);U[U.length]=[o,q,A]}function e(o){var q=H.pv;o=o.split(".");o[0]=parseInt(o[0],10);o[1]=parseInt(o[1],10)||0;o[2]=parseInt(o[2],10)||0;return q[0]>o[0]||q[0]==o[0]&&q[1]>o[1]||q[0]==o[0]&&q[1]==o[1]&&q[2]>=o[2]?true:false}function l(o,q,A,D){if(!(H.ie&&H.mac)){var G=B.getElementsByTagName("head")[0];if(G){A=A&&typeof A=="string"?A:"screen";if(D)fa=P=null;
if(!P||fa!=A){D=u("style");D.setAttribute("type","text/css");D.setAttribute("media",A);P=G.appendChild(D);if(H.ie&&H.win&&typeof B.styleSheets!=r&&B.styleSheets.length>0)P=B.styleSheets[B.styleSheets.length-1];fa=A}if(H.ie&&H.win)P&&typeof P.addRule==m&&P.addRule(o,q);else P&&typeof B.createTextNode!=r&&P.appendChild(B.createTextNode(o+" {"+q+"}"))}}}function t(o,q){if(ha){q=q?"visible":"hidden";if(T&&p(o))p(o).style.visibility=q;else l("#"+o,"visibility:"+q)}}function y(o){return/[\\\"<>\.;]/.exec(o)!=
null&&typeof encodeURIComponent!=r?encodeURIComponent(o):o}var r="undefined",m="object",s="application/x-shockwave-flash",v="SWFObjectExprInst",F=window,B=document,L=navigator,X=false,O=[k],R=[],aa=[],U=[],V,Z,ea,ga,T=false,Y=false,P,fa,ha=true,H=function(){var o=typeof B.getElementById!=r&&typeof B.getElementsByTagName!=r&&typeof B.createElement!=r,q=L.userAgent.toLowerCase(),A=L.platform.toLowerCase(),D=A?/win/.test(A):/win/.test(q);A=A?/mac/.test(A):/mac/.test(q);q=/webkit/.test(q)?parseFloat(q.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,
"$1")):false;var G=!+"\u000b1",J=[0,0,0],K=null;if(typeof L.plugins!=r&&typeof L.plugins["Shockwave Flash"]==m){if((K=L.plugins["Shockwave Flash"].description)&&!(typeof L.mimeTypes!=r&&L.mimeTypes[s]&&!L.mimeTypes[s].enabledPlugin)){X=true;G=false;K=K.replace(/^.*\s+(\S+\s+\S+$)/,"$1");J[0]=parseInt(K.replace(/^(.*)\..*$/,"$1"),10);J[1]=parseInt(K.replace(/^.*\.(.*)\s.*$/,"$1"),10);J[2]=/[a-zA-Z]/.test(K)?parseInt(K.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}}else if(typeof F.ActiveXObject!=r)try{var M=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(M)if(K=M.GetVariable("$version")){G=true;K=K.split(" ")[1].split(",");J=[parseInt(K[0],10),parseInt(K[1],10),parseInt(K[2],10)]}}catch(N){}return{w3:o,pv:J,wk:q,ie:G,win:D,mac:A}}();(function(){if(H.w3){if(typeof B.readyState!=r&&B.readyState=="complete"||typeof B.readyState==r&&(B.getElementsByTagName("body")[0]||B.body))b();if(!T){typeof B.addEventListener!=r&&B.addEventListener("DOMContentLoaded",b,false);if(H.ie&&H.win){B.attachEvent("onreadystatechange",
function(){if(B.readyState=="complete"){B.detachEvent("onreadystatechange",arguments.callee);b()}});F==top&&function(){if(!T){try{B.documentElement.doScroll("left")}catch(o){setTimeout(arguments.callee,0);return}b()}}()}H.wk&&function(){T||(/loaded|complete/.test(B.readyState)?b():setTimeout(arguments.callee,0))}();f(b)}}})();(function(){H.ie&&H.win&&window.attachEvent("onunload",function(){for(var o=U.length,q=0;q<o;q++)U[q][0].detachEvent(U[q][1],U[q][2]);o=aa.length;for(q=0;q<o;q++)d(aa[q]);for(var A in H)H[A]=
null;H=null;for(var D in swfobject)swfobject[D]=null;swfobject=null})})();return{registerObject:function(o,q,A,D){if(H.w3&&o&&q){var G={};G.id=o;G.swfVersion=q;G.expressInstall=A;G.callbackFn=D;R[R.length]=G;t(o,false)}else D&&D({success:false,id:o})},getObjectById:function(o){if(H.w3)return x(o)},embedSWF:function(o,q,A,D,G,J,K,M,N,W){var ba={success:false,id:q};if(H.w3&&!(H.wk&&H.wk<312)&&o&&q&&A&&D&&G){t(q,false);a(function(){A+="";D+="";var S={};if(N&&typeof N===m)for(var Q in N)S[Q]=N[Q];S.data=
o;S.width=A;S.height=D;Q={};if(M&&typeof M===m)for(var ca in M)Q[ca]=M[ca];if(K&&typeof K===m)for(var da in K)if(typeof Q.flashvars!=r)Q.flashvars+="&"+da+"="+K[da];else Q.flashvars=da+"="+K[da];if(e(G)){ca=h(S,Q,q);S.id==q&&t(q,true);ba.success=true;ba.ref=ca}else if(J&&C()){S.data=J;z(S,Q,q,W);return}else t(q,true);W&&W(ba)})}else W&&W(ba)},switchOffAutoHideShow:function(){ha=false},ua:H,getFlashPlayerVersion:function(){return{major:H.pv[0],minor:H.pv[1],release:H.pv[2]}},hasFlashPlayerVersion:e,
createSWF:function(o,q,A){if(H.w3)return h(o,q,A)},showExpressInstall:function(o,q,A,D){H.w3&&C()&&z(o,q,A,D)},removeSWF:function(o){H.w3&&d(o)},createCSS:function(o,q,A,D){H.w3&&l(o,q,A,D)},addDomLoadEvent:a,addLoadEvent:f,getQueryParamValue:function(o){var q=B.location.search||B.location.hash;if(q){if(/\?/.test(q))q=q.split("?")[1];if(o==null)return y(q);q=q.split("&");for(var A=0;A<q.length;A++)if(q[A].substring(0,q[A].indexOf("="))==o)return y(q[A].substring(q[A].indexOf("=")+1))}return""},expressInstallCallback:function(){if(Y){var o=
p(v);if(o&&V){o.parentNode.replaceChild(V,o);if(Z){t(Z,true);if(H.ie&&H.win)V.style.display="block"}ea&&ea(ga)}Y=false}}}}();steal.loaded("lib/swfobject/swfobject.js");
steal(/* "jquery" ,*/ "jquery/lang/string",function(b){var a=false,f=b.makeArray,k=b.isFunction,w=b.isArray,E=b.extend,x=b.String.getObject,C=function(n,h){return n.concat(f(h))},z=/xyz/.test(function(){})?/\b_super\b/:/.*/,I=function(n,h,j){j=j||n;for(var d in n)j[d]=k(n[d])&&k(h[d])&&z.test(n[d])?function(g,p){return function(){var u=this._super,c;this._super=h[g];c=p.apply(this,arguments);this._super=u;return c}}(d,n[d]):n[d]};clss=b.Class=function(){arguments.length&&clss.extend.apply(clss,arguments)};
E(clss,{proxy:function(n){var h=f(arguments),j;n=h.shift();w(n)||(n=[n]);j=this;for(var d=0;d<n.length;d++)if(typeof n[d]=="string"&&!k(this[n[d]]))throw"class.js "+(this.fullName||this.Class.fullName)+" does not have a "+n[d]+"method!";return function(){for(var g=C(h,arguments),p,u=n.length,c=0,e;c<u;c++)if(e=n[c]){if((p=typeof e=="string")&&j._set_called)j.called=e;g=(p?j[e]:e).apply(j,g||[]);if(c<u-1)g=!w(g)||g._use_call?[g]:g}return g}},newInstance:function(){var n=this.rawInstance(),h;if(n.setup)h=
n.setup.apply(n,arguments);if(n.init)n.init.apply(n,w(h)?h:arguments);return n},setup:function(n){this.defaults=E(true,{},n.defaults,this.defaults);return arguments},rawInstance:function(){a=true;var n=new this;a=false;return n},extend:function(n,h,j){function d(){if(!a)return this.constructor!==d&&arguments.length?arguments.callee.extend.apply(arguments.callee,arguments):this.Class.newInstance.apply(this.Class,arguments)}if(typeof n!="string"){j=h;h=n;n=null}if(!j){j=h;h=null}j=j||{};var g=this,
p=this.prototype,u,c,e,l;a=true;l=new this;a=false;I(j,p,l);for(u in this)if(this.hasOwnProperty(u))d[u]=this[u];I(h,this,d);if(n){e=n.split(/\./);c=e.pop();e=p=x(e.join("."),window,true);p[c]=d}E(d,{prototype:l,namespace:e,shortName:c,constructor:d,fullName:n});d.prototype.Class=d.prototype.constructor=d;g=d.setup.apply(d,C([g],arguments));if(d.init)d.init.apply(d,g||[]);return d}});clss.callback=clss.prototype.callback=clss.prototype.proxy=clss.proxy})();steal.loaded("jquery/class/class.js");
steal(/* "jquery" */).then(function(b){var a={undHash:/_|-/,colons:/::/,words:/([A-Z]+)([A-Z][a-z])/g,lowUp:/([a-z\d])([A-Z])/g,dash:/([a-z\d])([A-Z])/g,replacer:/\{([^\}]+)\}/g,dot:/\./},f=function(x,C,z){return x[C]!==undefined?x[C]:z&&(x[C]={})},k=function(x){return(x=typeof x)&&(x=="function"||x=="object")},w=function(x,C,z){x=x?x.split(a.dot):[];var I=x.length;C=b.isArray(C)?C:[C||window];var n,h,j,d=0;if(I==0)return C[0];for(;n=C[d++];){for(j=0;j<I-1&&k(n);j++)n=f(n,x[j],z);if(k(n)){h=f(n,x[j],z);
if(h!==undefined){z===false&&delete n[x[j]];return h}}}},E=b.String=b.extend(b.String||{},{getObject:w,capitalize:function(x){return x.charAt(0).toUpperCase()+x.substr(1)},camelize:function(x){x=E.classize(x);return x.charAt(0).toLowerCase()+x.substr(1)},classize:function(x,C){x=x.split(a.undHash);for(var z=0;z<x.length;z++)x[z]=E.capitalize(x[z]);return x.join(C||"")},niceName:function(x){return E.classize(x," ")},underscore:function(x){return x.replace(a.colons,"/").replace(a.words,"$1_$2").replace(a.lowUp,
"$1_$2").replace(a.dash,"_").toLowerCase()},sub:function(x,C,z){var I=[];I.push(x.replace(a.replacer,function(n,h){n=w(h,C,typeof z=="boolean"?!z:z);h=typeof n;if((h==="object"||h==="function")&&h!==null){I.push(n);return""}else return""+n}));return I.length<=1?I[0]:I},_regs:a})});steal.loaded("jquery/lang/string/string.js");steal("jquery/event").then(function(b){var a=jQuery.cleanData;b.cleanData=function(f){for(var k=0,w;(w=f[k])!==undefined;k++)b(w).triggerHandler("destroyed");a(f)}});steal.loaded("jquery/event/destroyed/destroyed.js");
steal(/* "jquery" */);steal.loaded("jquery/event/event.js");
steal(/* "jquery" */).then(function(b){var a=function(c){return c.replace(/^\/\//,"").replace(/[\/\.]/g,"_")},f=1,k,w,E,x=function(c){return c&&b.isFunction(c.always)},C=function(c){var e=[];if(x(c))return[c];else for(var l in c)x(c[l])&&e.push(c[l]);return e},z=function(c){return b.isArray(c)&&c.length===3&&c[1]==="success"?c[0]:c};k=b.View=function(c,e,l,t){if(typeof l==="function"){t=l;l=undefined}var y=C(e);if(y.length){var r=b.Deferred();y.push(E(c,true));b.when.apply(b,y).then(function(s){var v=b.makeArray(arguments),
F=v.pop()[0];if(x(e))e=z(s);else for(var B in e)if(x(e[B]))e[B]=z(v.shift());v=F(e,l);r.resolve(v);t&&t(v)});return r.promise()}else{var m;y=typeof t==="function";r=E(c,y);if(y){m=r;r.done(function(s){t(s(e,l))})}else r.done(function(s){m=s(e,l)});return m}};w=function(c,e){if(!c.match(/[^\s]/))throw"$.View ERROR: There is no template or an empty template at "+e;};E=function(c,e){return b.ajax({url:c,dataType:"view",async:e})};b.ajaxTransport("view",function(c,e){c=e.url;var l=c.match(/\.[\w\d]+$/),
t,y,r,m=c,s,v=function(F){F=t.renderer(r,F);if(k.cache)k.cached[r]=F;return{view:F}};if(y=document.getElementById(c))l=y.type.match(/\/[\d\w]+$/)[0].replace(/^\//,".");if(!l){l=k.ext;m+=k.ext}r=a(m);if(m.match(/^\/\//))m=typeof steal==="undefined"?"/"+m.substr(2):steal.root.mapJoin(m.substr(2));t=k.types[l];return{send:function(F,B){if(k.cached[r])return B(200,"success",{view:k.cached[r]});else if(y)B(200,"success",v(y.innerHTML));else s=b.ajax({async:e.async,url:m,dataType:"text",error:function(){w("",
m);B(404)},success:function(L){w(L,m);B(200,"success",v(L))}})},abort:function(){s&&s.abort()}}});b.extend(k,{hookups:{},hookup:function(c){var e=++f;k.hookups[e]=c;return e},cached:{},cache:true,register:function(c){this.types["."+c.suffix]=c;window.steal&&steal.type(c.suffix+" view js",function(e,l,t){l=k.types["."+e.type];var y=a(e.rootSrc);e.text=l.script(y,e.text);t()})},types:{},ext:".ejs",registerScript:function(c,e,l){return"$.View.preload('"+e+"',"+k.types["."+c].script(e,l)+");"},preload:function(c,
e){k.cached[c]=function(l,t){return e.call(l,l,t)}}});window.steal&&steal.type("view js",function(c,e,l){e=k.types["."+c.type];var t=a(c.rootSrc);c.text="steal('"+(e.plugin||"jquery/view/"+c.type)+"').then(function($){$.View.preload('"+t+"',"+c.text+");\n})";l()});var I,n,h,j,d,g,p;I=function(c){var e=b.fn[c];b.fn[c]=function(){var l=b.makeArray(arguments),t,y,r=this;if(x(l[0])){l[0].done(function(m){n.call(r,[m],e)});return this}else if(h(l)){if(t=d(l)){y=l[t];l[t]=function(m){n.call(r,[m],e);y.call(r,
m)};k.apply(k,l);return this}l=k.apply(k,l);if(x(l)){l.done(function(m){n.call(r,[m],e)});return this}else l=[l]}return n.call(this,l,e)}};n=function(c,e){var l;for(var t in k.hookups)break;if(t&&c[0]&&j(c[0])){l=k.hookups;k.hookups={};c[0]=b(c[0])}e=e.apply(this,c);l&&g(c[0],l);return e};h=function(c){var e=typeof c[1];return typeof c[0]=="string"&&(e=="object"||e=="function")&&!c[1].nodeType&&!c[1].jquery};j=function(c){if(c.jquery||c.nodeType===1)return true;else if(typeof c==="string"){c=b.trim(c);
return c.substr(0,1)==="<"&&c.substr(c.length-1,1)===">"&&c.length>=3}else return false};d=function(c){return typeof c[3]==="function"?3:typeof c[2]==="function"&&2};g=function(c,e){var l,t=0,y,r;c=c.filter(function(){return this.nodeType!=3});c=c.add("[data-view-id]",c);for(l=c.length;t<l;t++)if(c[t].getAttribute&&(y=c[t].getAttribute("data-view-id"))&&(r=e[y])){r(c[t],y);delete e[y];c[t].removeAttribute("data-view-id")}b.extend(k.hookups,e)};b.fn.hookup=function(){var c=k.hookups;k.hookups={};g(this,
c);return this};p=["prepend","append","after","before","text","html","replaceWith","val"];for(var u=0;u<p.length;u++)I(p[u])});steal.loaded("jquery/view/view.js");steal("jquery/lang/string",function(b){b.String.rsplit=function(a,f){for(var k=f.exec(a),w=[],E;k!==null;){E=k.index;if(E!==0){w.push(a.substring(0,E));a=a.slice(E)}w.push(k[0]);a=a.slice(k[0].length);k=f.exec(a)}a!==""&&w.push(a);return w}});steal.loaded("jquery/lang/string/rsplit/rsplit.js");
(function(b){if(typeof b.browser==="undefined"||!b.browser)b.extend({});var a={flash:{activex:["ShockwaveFlash.ShockwaveFlash","ShockwaveFlash.ShockwaveFlash.3","ShockwaveFlash.ShockwaveFlash.4","ShockwaveFlash.ShockwaveFlash.5","ShockwaveFlash.ShockwaveFlash.6","ShockwaveFlash.ShockwaveFlash.7"],plugin:/flash/gim},sl:{activex:["AgControl.AgControl"],plugin:/silverlight/gim},pdf:{activex:["acroPDF.PDF.1","PDF.PdfCtrl.1","PDF.PdfCtrl.4","PDF.PdfCtrl.5","PDF.PdfCtrl.6"],plugin:/adobe\s?acrobat/gim},
qtime:{activex:["QuickTime.QuickTime","QuickTimeCheckObject.QuickTimeCheck.1","QuickTime.QuickTime.4"],plugin:/quicktime/gim},wmp:{activex:["WMPlayer.OCX","MediaPlayer.MediaPlayer.1"],plugin:/(windows\smedia)|(Microsoft)/gim},shk:{activex:["SWCtl.SWCtl","SWCt1.SWCt1.7","SWCt1.SWCt1.8","SWCt1.SWCt1.9","ShockwaveFlash.ShockwaveFlash.1"],plugin:/shockwave/gim},rp:{activex:["RealPlayer","rmocx.RealPlayer G2 Control.1"],plugin:/realplayer/gim}},f=function(k){if(window.ActiveXObject){b.browser[k]=false;
for(i=0;i<a[k].activex.length;i++)try{new ActiveXObject(a[k].activex[i]);b.browser[k]=true}catch(w){}}else b.each(navigator.plugins,function(){if(this.name.match(a[k].plugin)){b.browser[k]=true;return false}else b.browser[k]=false})};b.each(a,function(k){f(k)})})(jQuery);steal.loaded("lib/jquery-jqplugin/jquery-jqplugin.js");
(function(b){function a(){for(var n=navigator.plugins,h=0;h<n.length;h++)if(n[h].filename=="np-mswmp.dll")return true;return false}function f(){var n="";for(var h in b.fn.media.defaults.players){if(n.length)n+=",";n+=b.fn.media.defaults.players[h].types}return new RegExp("\\.("+n.replace(/,/ig,"|")+")\\b")}function k(n){return function(h,j){return x(h,j,n)}}function w(n){return"0123456789".indexOf(n)>-1}function E(n,h){h=h||{};var j=b(n),d=n.className||"",g=b.metadata?j.metadata():b.meta?j.data():
{};g=g||{};var p=g.width||parseInt((d.match(/\bw:(\d+)/)||[])[1]||0)||parseInt((d.match(/\bwidth:(\d+)/)||[])[1]||0),u=g.height||parseInt((d.match(/\bh:(\d+)/)||[])[1]||0)||parseInt((d.match(/\bheight:(\d+)/)||[])[1]||0);if(p)g.width=p;if(u)g.height=u;if(d)g.cls=d;for(d=0;d<n.attributes.length;d++){var c=n.attributes[d];p=b.trim(c.name);if(p.indexOf("data-")===0){p=p.substring(5);g[p]=c.value}}c=b.fn.media.defaults;var e=h,l=g,t={params:{bgColor:h.bgColor||b.fn.media.defaults.bgColor}},y=b.extend({},
c,e,l);b.each(["attrs","params","flashvars","silverlight"],function(r,m){y[m]=b.extend({},t[m]||{},c[m]||{},e[m]||{},l[m]||{})});if(typeof y.caption=="undefined")y.caption=j.text();y.src=y.src||j.attr("href")||j.attr("src")||"unknown";return y}function x(n,h,j){var d=b(n),g=b.fn.media.defaults.players[j];if(j=="iframe"){g=b('<iframe width="'+h.width+'" height="'+h.height+'" >');g.attr("src",h.src);g.css("backgroundColor",g.bgColor)}else if(j=="img"){g=b("<img>");g.attr("src",h.src);h.width&&g.attr("width",
h.width);h.height&&g.attr("height",h.height);g.css("backgroundColor",g.bgColor)}else if(C){var p=['<object width="'+h.width+'" height="'+h.height+'" '];for(var u in h.attrs)p.push(u+'="'+h.attrs[u]+'" ');for(u in g.ieAttrs||{}){var c=g.ieAttrs[u];if(u=="codebase"&&window.location.protocol=="https:")c=c.replace("http","https");p.push(u+'="'+c+'" ')}p.push("></object>");c=['<param name="'+(g.oUrl||"src")+'" value="'+h.src+'">'];for(u in h.params)c.push('<param name="'+u+'" value="'+h.params[u]+'">');
g=document.createElement(p.join(""));for(u=0;u<c.length;u++)g.appendChild(document.createElement(c[u]))}else if(h.standards){p=['<object type="'+g.mimetype+'" width="'+h.width+'" height="'+h.height+'"'];h.src&&p.push(' data="'+h.src+'" ');if(b.browser.msie)for(u in g.ieAttrs||{}){c=g.ieAttrs[u];if(u=="codebase"&&window.location.protocol=="https:")c=c.replace("http","https");p.push(u+'="'+c+'" ')}p.push(">");p.push('<param name="'+(g.oUrl||"src")+'" value="'+h.src+'">');for(u in h.params)u=="wmode"&&
j!="flash"||p.push('<param name="'+u+'" value="'+h.params[u]+'">');p.push("<div><p><strong>"+g.title+" Required</strong></p><p>"+g.title+' is required to view this media. <a href="'+g.pluginspage+'">Download Here</a>.</p></div>');p.push("</object>")}else{p=['<embed width="'+h.width+'" height="'+h.height+'" style="display:block"'];h.src&&p.push(' src="'+h.src+'" ');for(u in h.attrs)p.push(u+'="'+h.attrs[u]+'" ');for(u in g.eAttrs||{})p.push(u+'="'+g.eAttrs[u]+'" ');for(u in h.params)u=="wmode"&&j!=
"flash"||p.push(u+'="'+h.params[u]+'" ');p.push("></embed>")}n=b("<div"+(n.id?' id="'+n.id+'"':"")+(h.cls?' class="'+h.cls+'"':"")+">");d.after(n).remove();C||j=="iframe"||j=="img"?n.append(g):n.html(p.join(""));h.caption&&b("<div>").appendTo(n).html(h.caption);return n}var C=b.browser.msie&&b.browser.version<9;b.fn.media=function(n,h,j){if(n=="undo")return this.each(function(){var d=b(this),g=d.data("media.origHTML");g&&d.replaceWith(g)});return this.each(function(){if(typeof n=="function"){j=h;
h=n;n={}}var d=E(this,n);typeof h=="function"&&h(this,d);var g=f().exec(d.src.toLowerCase())||[""];d.type?(g[0]=d.type):g.shift();for(var p=0;p<g.length;p++){fn=g[p].toLowerCase();if(w(fn[0]))fn="fn"+fn;if(b.fn.media[fn]){g=b.fn.media[fn+"_player"];if(!d.params)d.params={};if(g)d.params[g.autoplayAttr||"autoplay"]=g.autoplayAttr=="autostart"?d.autoplay?1:0:d.autoplay?true:false;p=b.fn.media[fn](this,d);p.css("backgroundColor",d.bgColor).width(d.width);if(d.canUndo){var u=b("<div></div>").append(this);
p.data("media.origHTML",u.html())}typeof j=="function"&&j(this,p[0],d,g.name);break}}})};b.fn.media.mapFormat=function(n,h){if(!(!n||!h||!b.fn.media.defaults.players[h])){n=n.toLowerCase();if(w(n[0]))n="fn"+n;b.fn.media[n]=b.fn.media[h];b.fn.media[n+"_player"]=b.fn.media.defaults.players[h]}};b.fn.media.defaults={standards:true,canUndo:true,width:400,height:400,autoplay:0,bgColor:"#ffffff",params:{wmode:"transparent"},attrs:{},flvKeyName:"file",flashvars:{},flashVersion:"7",expressInstaller:null,
flvPlayer:"mediaplayer.swf",mp3Player:"mediaplayer.swf",silverlight:{inplaceInstallPrompt:"true",isWindowless:"true",framerate:"24",version:"0.9",onError:null,onLoad:null,initParams:null,userContext:null}};b.fn.media.defaults.players={flash:{name:"flash",title:"Flash",types:"flv,mp3,swf",mimetype:"application/x-shockwave-flash",pluginspage:"http://www.adobe.com/go/getflashplayer",ieAttrs:{classid:"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",type:"application/x-oleobject",codebase:"http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version="+
b.fn.media.defaults.flashVersion}},quicktime:{name:"quicktime",title:"QuickTime",mimetype:"video/quicktime",pluginspage:"http://www.apple.com/quicktime/download/",types:"aif,aiff,aac,au,bmp,gsm,mov,mid,midi,mpg,mpeg,mp4,m4a,psd,qt,qtif,qif,qti,snd,tif,tiff,wav,3g2,3gp",ieAttrs:{classid:"clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B",codebase:"http://www.apple.com/qtactivex/qtplugin.cab"}},realplayer:{name:"real",title:"RealPlayer",types:"ra,ram,rm,rpm,rv,smi,smil",mimetype:"audio/x-pn-realaudio-plugin",
pluginspage:"http://www.real.com/player/",autoplayAttr:"autostart",ieAttrs:{classid:"clsid:CFCDAA03-8BE4-11cf-B84B-0020AFBBCCFA"}},winmedia:{name:"winmedia",title:"Windows Media",types:"asx,asf,avi,wma,wmv",mimetype:b.browser.mozilla&&a()?"application/x-ms-wmp":"application/x-mplayer2",pluginspage:"http://www.microsoft.com/Windows/MediaPlayer/",autoplayAttr:"autostart",oUrl:"url",ieAttrs:{classid:"clsid:6BF52A52-394A-11d3-B153-00C04F79FAA6",type:"application/x-oleobject"}},img:{name:"img",title:"Image",
types:"gif,png,jpg"},iframe:{name:"iframe",types:"html,pdf"},silverlight:{name:"silverlight",types:"xaml"}};var z=1;for(var I in b.fn.media.defaults.players)b.each(b.fn.media.defaults.players[I].types.split(","),function(n,h){if(w(h[0]))h="fn"+h;b.fn.media[h]=b.fn.media[I]=k(I);b.fn.media[h+"_player"]=b.fn.media.defaults.players[I]});b.fn.media.swf=function(n,h){if(!window.SWFObject&&!window.swfobject){if(h.flashvars){var j=[];for(var d in h.flashvars)j.push(d+"="+h.flashvars[d]);if(!h.params)h.params=
{};h.params.flashvars=j.join("&")}return x(n,h,"flash")}j=b("<div"+(n.id?' id="'+n.id+'"':"")+(h.cls?' class="'+h.cls+'"':"")+">");if(window.swfobject){b(n).after(j).appendTo(j);if(!n.id)n.id="movie_player_"+z++;swfobject.embedSWF(h.src,n.id,h.width,h.height,h.flashVersion,h.expressInstaller,h.flashvars,h.params,h.attrs)}else{b(n).after(j).remove();n=new SWFObject(h.src,"movie_player_"+z++,h.width,h.height,h.flashVersion,h.bgColor);h.expressInstaller&&n.useExpressInstall(h.expressInstaller);for(var g in h.params)g!=
"bgColor"&&n.addParam(g,h.params[g]);for(d in h.flashvars)n.addVariable(d,h.flashvars[d]);n.write(j[0])}h.caption&&b("<div>").appendTo(j).html(h.caption);return j};b.fn.media.flv=b.fn.media.mp3=function(n,h){var j=h.src,d=/\.mp3\b/i.test(j)?b.fn.media.defaults.mp3Player:b.fn.media.defaults.flvPlayer,g=h.flvKeyName;j=encodeURIComponent(j);h.src=d;h.src=h.src+"?"+g+"="+j;d={};d[g]=j;h.flashvars=b.extend({},d,h.flashvars);return b.fn.media.swf(n,h)};b.fn.media.xaml=function(n,h){if(window.Silverlight){var j=
{width:h.width,height:h.height,background:h.bgColor,inplaceInstallPrompt:h.silverlight.inplaceInstallPrompt,isWindowless:h.silverlight.isWindowless,framerate:h.silverlight.framerate,version:h.silverlight.version},d={onError:h.silverlight.onError,onLoad:h.silverlight.onLoad},g=n.id?' id="'+n.id+'"':"",p=h.id||"AG"+z++;g=b("<div"+g+(h.cls?' class="'+h.cls+'"':"")+">");b(n).after(g).remove();Silverlight.createObjectEx({source:h.src,initParams:h.silverlight.initParams,userContext:h.silverlight.userContext,
id:p,parentElement:g[0],properties:j,events:d});h.caption&&b("<div>").appendTo(g).html(h.caption);return g}else if(!b.fn.media.xaml.warning){b.fn.media.xaml.warning=1;alert("You must include the Silverlight.js script.")}}})(jQuery);steal.loaded("lib/jquery-media/jquery-media.js");
(function(b,a){var f=function(){};f.prototype={initialize:function(){this.userAgent=navigator.userAgent;this.isiPad=this.userAgent.match(/iPad/i)!=null;this.isiPhone=this.userAgent.match(/iPhone/i)!=null;this.isAndroid=this.userAgent.match(/Android/i)!=null;this.screenHeight=this.screenWidth=screen.width;this.isPhone=this.screenHeight<360;this.isTablet=this.screenHeight>=360&&this.screenHeight<=768;this.isDesktop=this.screenHeight>768;this.hasHTML5VideoCapability=!!document.createElement("video").canPlayType;
this.flashPlayerVersion=swfobject.getFlashPlayerVersion();this.hasFlashPlayerCapability=this.flashPlayerVersion.major>=10},adapt:function(j){this.userAgent||this.initialize();j=b.extend({},b.fn.strobemediaplayback.defaults,j);this.changed=true;for(var d=0,g=this.rules.length;this.changed;){this.changed=false;for(d=0;d<g;d++)this.rules[d](this,j);this.changed=false}return j},setOption:function(j,d,g){if(!j.hasOwnProperty(d)||j[d]!=g){j[d]=g;this.changed=true}},rules:[function(j,d){if(d.favorFlashOverHtml5Video&&
j.hasFlashPlayerCapability)j.setOption(d,"useHTML5",false);else if(!d.favorFlashOverHtml5Video&&j.hasHTML5VideoCapability)j.setOption(d,"useHTML5",true);else d.favorFlashOverHtml5Video?j.setOption(d,"useHTML5",!j.hasFlashPlayerCapability):j.setOption(d,"useHTML5",j.hasHTML5VideoCapability)},function(j,d){j.isiPhone&&j.setOption(d,"javascriptControls",false)},function(j,d){j.isiPad&&j.setOption(d,"disabledControls",".volume")},function(j,d){if(!j.hasFlashPlayerCapability&&!j.hasHTML5VideoCapability){j.setOption(d,
"javascriptControls",false);j.setOption(d,"displayAlternativeContent",true)}}]};b.fn.adaptiveexperienceconfigurator=new f;var k=function(j,d){this.element=j;this.$element=b(j);this.options=b.extend({},b.fn.strobemediaplayback.defaults,d)},w=null;k.prototype={initialize:function(){this.options=b.fn.adaptiveexperienceconfigurator.adapt(this.options);if(this.options.useHTML5){var j=b("<video></video>");j.attr("id",this.options.id);j.attr("class","smp_video");this.options.preload?j.attr("preload",this.options.preload):
j.attr("preload","none");j.attr("width",this.options.width);j.attr("height",this.options.height);j.attr("src",this.options.src);this.options.loop&&j.attr("loop","loop");this.options.autoPlay&&j.attr("autoplay","autoplay");this.options.controlBarMode!="none"&&j.attr("controls","controls");this.options.poster!=""&&j.attr("poster",this.options.poster);this.$element.replaceWith(j);this.$video=j;this.video=j[0]}else{this.options.queryString=b.fn.strobemediaplayback.generateQueryString(this.options);j=
this.options;j.javascriptCallbackFunction="$.fn.strobemediaplayback.triggerHandler";var d="direct",g="sameDomain",p="";if(this.options.wmode!=a)d=this.options.wmode;if(this.options.allowScriptAccess!=a)g=this.options.allowScriptAccess;if(this.options.poster!=""){p=this.options.poster;j.loadImage=p}d={allowFullScreen:"true",wmode:d,allowScriptAccess:g,poster:p};g={id:this.options.id,name:this.options.id};w=this;swfobject.embedSWF(this.options.swf,this.$element.attr("id"),this.options.width,this.options.height,
this.options.minimumFlashPlayerVersion,this.options.expressInstallSwfUrl,j,d,g,this.onFlashEmbedComplete);this.monitor=new h(null);this.$video=this.monitor.$videoElement;this.video=this.monitor.videoElement;E[this.options.id]=this.monitor}},onFlashEmbedComplete:function(j){if(!j.success&&b.fn.adaptiveexperienceconfigurator.hasHTML5VideoCapability){w.useHTML5=true;w.initialize()}}};b.fn.strobemediaplayback=function(j){var d=[],g,p=null;this.each(function(){var u=new k(this,j);d.push(u)});for(g=0;g<
d.length;g++){d[g].initialize();if(p==null)p=d[g].$video;else p.push(d[g].video)}return p};b.fn.strobemediaplayback.defaults={favorFlashOverHtml5Video:true,swf:"/lib/jquery-strobemediaplayback/StrobeMediaPlayback.swf",javascriptCallbackFunction:"$.fn.strobemediaplayback.triggerHandler",minimumFlashPlayerVersion:"10.0.0",expressInstallSwfUrl:"expressInstall.swf",autoPlay:false,loop:false,controlBarMode:"docked",poster:""};b.fn.strobemediaplayback.parseQueryString=function(j){var d={};j=j.split("&");
for(var g,p=j.length,u=0;u<p;u++){g=j[u].split("=");if(g[1]=="true"||g[1]=="false")d[g[0]]=g[1]=="true";else{var c=parseFloat(g[1]);d[g[0]]=isNaN(c)?g[1]:c}}return d};b.fn.strobemediaplayback.generateQueryString=function(j){var d=[];for(var g in j){d.length>0&&d.push("&");d.push(encodeURIComponent(g));d.push("=");d.push(j[g])}return d.join("")};var E={},x={};b.fn.strobemediaplayback.triggerHandler=function(j,d,g){var p=E[j];if(typeof p!="undefined"){if(typeof x[j]=="undefined"){strobeMediaPlayback=
document.getElementById(j);x[j]=strobeMediaPlayback;p.strobeMediaPlayback=strobeMediaPlayback;p.videoElement.play=jQuery.proxy(strobeMediaPlayback.play2,p.strobeMediaPlayback);p.videoElement.pause=jQuery.proxy(strobeMediaPlayback.pause,p.strobeMediaPlayback);p.videoElement.load=jQuery.proxy(p.load,p);p.videoElement.strobeMediaPlayback=strobeMediaPlayback;n(p)}p.update(g,[d],p)}};var C="src preload currentTime defaultPlaybackRate playbackRate autoplay loop controls volume muted".split(" "),z="played seekable buffered".split(" "),
I={start:function(j){return this._start[j]},end:function(j){return this._end[j]}},n=function(j){for(var d=C.length;d--;){var g=C[d];if(j.cc.hasOwnProperty(g)&&j.videoElement.hasOwnProperty(g)&&j.cc[g]!=j.videoElement[g]){var p="set"+g.charAt(0).toUpperCase()+g.substring(1);j.strobeMediaPlayback[p](j.videoElement[g]);j.cc[g]=j.videoElement[g]}}setTimeout(function(){n(j)},500)},h=function(){this.videoElement={duration:0,currentTime:0,paused:true,muted:false};this.cc={duration:0,currentTime:0,paused:true,
muted:false};this.$videoElement=b(this.videoElement)};h.prototype={load:function(){this.strobeMediaPlayback.setSrc(this.videoElement.src);this.strobeMediaPlayback.load()},update:function(j,d,g){var p;for(p in j)if(!(jQuery.inArray("emptied",d)<0&&g.cc.hasOwnProperty(p)&&g.videoElement.hasOwnProperty(p)&&g.cc[p]!=g.videoElement[p]&&!isNaN(g.cc[p])&&!isNaN(g.videoElement[p]))){g.cc[p]=j[p];g.videoElement[p]=j[p];if(jQuery.inArray(p,z)>=0){g.videoElement[p].start=I.start;g.videoElement[p].end=I.end}}if(d)for(j=
d.length;j--;)g.$videoElement.triggerHandler(d[j])}}})(jQuery);if(typeof org=="undefined")var org={};if(typeof org.strobemediaplayback=="undefined")org.strobemediaplayback={};if(typeof org.strobemediaplayback.proxied=="undefined")org.strobemediaplayback.proxied={};
org.strobemediaplayback.triggerHandler=function(b,a,f){if(a=="onJavaScriptBridgeCreated")typeof onJavaScriptBridgeCreated=="function"&&onJavaScriptBridgeCreated(b);else typeof org.strobemediaplayback.proxied[b]!="undefined"&&org.strobemediaplayback.proxied[b].update(f,[a],org.strobemediaplayback.proxied[b])};steal.loaded("lib/jquery-strobemediaplayback/jquery-strobemediaplayback.js");
