var commands=Array(10),commandIter=0,xMousePos=0,yMousePos=0,xMousePosMax=0,yMousePosMax=0,objPopUp=null,popupCancel=!1,popupHold=!1,popupTimerSet=!1,popupId;commands[commandIter++]="globalInit()";commands[commandIter++]="unfoldCurrent()";commands[commandIter++]="startList()";onLoad=function(){for(var a=0;a<commandIter;a++)eval(commands[a])};function setImageSrc(a,b,c){null!=a&&(null==c&&(c=document.images),null!=c[b]&&a.src&&null!=c[b]&&(a.src=c[b].src))}
function browserDetect(){this.isNS4=document.layers&&"Netscape"==navigator.appName&&4==parseInt(navigator.appVersion)?!0:!1;this.isIE4=document.all&&-1<navigator.appName.indexOf("Microsoft")&&4==parseInt(navigator.appVersion)?!0:!1;this.isIE5=document.getElementById&&-1<navigator.appName.indexOf("Microsoft")?!0:!1;this.isNS6=document.getElementById&&"Netscape"==navigator.appName&&4<parseInt(navigator.appVersion)?!0:!1;this.isOP5=document.getElementById&&"Opera"==navigator.appName&&4<parseInt(navigator.appVersion)?
!0:!1;this.isMac=-1!=navigator.userAgent.toLowerCase().indexOf("mac")}var app=new browserDetect;function isHScrollbar(){return document.documentElement.scrollWidth>document.documentElement.clientWidth?!0:!1}function isVScrollbar(){return document.documentElement.scrollHeight>document.documentElement.clientHeight?!0:!1}function includeJsFile(a){app.isNS4||document.writeln('<script language="javascript" src="'+a+'" type="text/javascript">\x3c/script>')}
function includeJsFileAlternative(a,b){app.isNS4?document.writeln('<script language="javascript" src="'+b+'" type="text/javascript"/>'):includeJsFile(a)}function submitSearch(){document.forms.searchForm.submit()}function createHidden(a,b,c){var d=document.createElement("input");d.type="hidden";d.name=b;d.value=c;document.forms[a].appendChild(d)}
function setSubmitProperty(a,b,c,d){return null==d||confirm(d)?(null==document.forms[a].elements[b]?createHidden(a,b,c):document.forms[a].elements[b].value=c,!0):!1}function submitForm(a,b,c){null!=b&&setSubmitProperty(a,b,c);document.forms[a].submit()}function submitSelected(a,b,c){if(!document.forms[a]||!document.forms[a].elements[b])return!1;if(""==document.forms[a].elements[b].value)return alert(c),!1;document.forms[a].submit()}
function isClass(a,b){if(null==a||1!=a.nodeType)return!1;for(var c=a.className.split(" "),d=0;d<c.length;d++)if(c[d]==b)return!0;return!1}function switchClass(a,b,c){if(null!=a){for(var d=a.className.split(" "),f="",e="",g=0;g<d.length;g++)d[g]==b?""!=c&&(f=f+e+c):f=f+e+d[g],e=" ";a.className=f}}function appendClass(a,b,c){if(null!=a){if(c&&isClass(a,b))return!1;a.className=a.className+" "+b}}
function findElementsOfClass(a,b){if(null!=a){for(var c=a.firstChild,d=[],f=0;c;){isClass(c,b)&&(d[f]=c,f++);for(var e=findElementsOfClass(c,b),g=0;g<e.length;g++)d[f]=e[g],f++;c=c.nextSibling}return d}}function createCookie(a,b,c,d){if(c){var f=new Date;f.setTime(f.getTime()+864E5*c);c="; expires="+f.toGMTString()}else c="";f="";d&&(f="; path="+d);document.cookie=a+"="+b+c+f}
function readCookie(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return null}function getCookie(a){a=("; "+document.cookie).split("; "+a+"=");if(2==a.length)return a.pop().split(";").shift()}function eraseCookie(a){createCookie(a,"",-1)}function eraseSiteCookie(a){createCookie(a,"",-1,"/")}
function erasePreviousList(){eraseCookie("OnsemiPreviousProducts");document.forms.previousProducts.elements.id.value="";document.forms.previousProducts.elements.id.disabled="true"}function clearInput(a,b,c){null==b&&(b="Enter Part#/Keyword");a.value==b&&(a.value="",null!=c&&(a.style.color=c))}function defaultInputVal(a,b,c){null==b&&(b="Enter Part#/Keyword");""==a.value&&(a.value=b,null!=c&&(a.style.color=c))}
function setChecked(a,b){null==b&&(b=!0);var c=document.getElementById(a);null!=c&&(c.checked=b)}
function cntrSubmit(a){cntAlphaNum=0;for(allowedChars='*-.,/ "'.split("");32==a.charCodeAt(a.length-1);)a=a.substr(0,a.length-1);for(i=0;i<a.length;i++)if(asc=a.toUpperCase().charCodeAt(i),48<=asc&&57>=asc||65<=asc&&90>=asc)cntAlphaNum++;else{found=!1;for(j=0;j<allowedChars.length;j++)asc==allowedChars[j].charCodeAt(0)&&(found=!0);if(!found){chars="";for(k=0;k<allowedChars.length;k++)chars+=", "+allowedChars[k];alert("Only the following characters can be entered search : {A-Z, 0-9"+chars+" }");return!1}}return 3>
cntAlphaNum?(alert("You must enter at least 3 characters."),!1):!0}function scrollbarDetect(){this.hasVScroll=this.hasHScroll=!1;this.initHeight=this.initWidth=0}var scroll=new scrollbarDetect;
function globalInit(){scroll.hasHScroll=isHScrollbar();scroll.hasVScroll=isVScrollbar();scroll.initWidth=document.documentElement.clientWidth;scroll.initHeight=document.documentElement.clientHeight;$("html").mousemove(function(a){xMousePos=a.pageX;yMousePos=a.pageY});void 0!=$().result&&$("#query").autocomplete("/PowerSolutions/solrAutocomplete.do",{autoFill:!1,cacheLength:0,minChars:3,selectFirst:!1}).result(function(){$("#searchType").val("others");$("#searchForm").submit()})}
function JustSoPicWindow(a,b,c,d,f,e,g){var l;""==f&&(f="#FFFFFF");var h=screen.width,m=screen.height;740>h&&(l=.9);740<=h&835>h&&(l=.91);835<=h&&(l=.93);if(b>h){var p=h/b;b=h;c*=p}c>m-10&&(b*=m/c,c=m);p=h-10;var q=m*l-10;c>q&&(c*=l,b*=l);var r=0,t=0;"hug image"==e&&(""==g&&(g=0),e=c-0+2*g,e<q&&(q=e),g=b-0+2*g,g<p&&(p=g),100>q&&(q=100),100>p&&(p=100),t=(m-q/l-10)/2,r=(h-p-10)/2);if(c>m*l-10||b>h-10)c-=10,b-=10;t=parseInt(t);r=parseInt(r);p=parseInt(p);q=parseInt(q);if(-1!=navigator.userAgent.toLowerCase().indexOf("opera"))for(b=
["parent"],b[1]=a,document.MM_returnValue=!1,a=0;a<b.length-1;a+=2)eval(b[a]+".location='"+b[a+1]+"'");else newWindow=window.open("vwd_justso.htm","newWindow","width="+p+",height="+q+",left="+r+",top="+t),newWindow.document.open(),newWindow.document.write("<html><title>"+d+'</title><body leftmargin="0" topmargin="0" marginheight="0" marginwidth="0" bgcolor='+f+' onBlur="self.close()" onClick="self.close()">'),newWindow.document.write("<table width="+b+' border="0" cellspacing="0" cellpadding="0" align="center" height='+
q+" ><tr><td>"),newWindow.document.write('<img src="'+a+'" width='+b+" height="+c+' alt="Klikni na obr?zek pro zav?en? okna" >'),newWindow.document.write("</td></tr></table></body></html>"),newWindow.document.close(),newWindow.focus()}function gotoURL(a){window.location.href=a}function setFocus(a){$("#"+a).focus()}function setFormField(a,b,c){a=document.forms[a];null!=a&&(b=a.elements[b],null!=b&&(b.value=c))}
function popupBlock(a){objPopUp=document.getElementById(a);null!=objPopUp&&$(objPopUp).css("display","block")}function hideBlock(a){objPopUp=document.getElementById(a);null!=objPopUp&&$(objPopUp).css("display","none")}function xmlhttpGet(a){window.XMLHttpRequest?this.xmlHttpReq=new XMLHttpRequest:window.ActiveXObject&&(this.xmlHttpReq=new ActiveXObject("Microsoft.XMLHTTP"));this.xmlHttpReq.open("GET",a,!0);this.xmlHttpReq.send()}
function popupData(a){if(popupCancel)popupCancel=!1;else if(null==objPopUp&&(objPopUp=$("#"+a),null!=objPopUp)){a=objPopUp.width();var b=objPopUp.height(),c=xMousePos+5,d=yMousePos-5-b;c+a>=$(window).width()+$(window).scrollLeft()&&(c-=a+10);d<=$(window).scrollTop()&&(d+=b+10);$(objPopUp).css({left:c+"px",top:d+"px",visibility:"visible"})}}
function popHide(a){null!=objPopUp&&(0<a&&!popupHold?popupTimerSet||(self.setTimeout("popHide()",a),popupTimerSet=!0):(popupTimerSet=!1,popupHold?popupHold=!1:($(objPopUp).css("visibility","hidden"),objPopUp=null)))}function popupText(a,b){popupCancel?popupCancel=!1:(objPopUp=document.getElementById(b),objPopUp.innerHTML=a,objPopUp=null,popupData(b))}function cancelPopup(){popupCancel=!0}function holdPopup(){popupHold=!0}
function AllowOnlyNumeric(a){if(window.event)var b=window.event.keyCode;else a.which&&(b=a.which);47<b&&58>b||(window.event?window.event.returnValue=null:a.which&&a.preventDefault())}function processAction(a,b){document.forms.fState.elements.action.value=a;document.forms.fState.elements.actionData.value=b;document.forms.fState.submit()}window.onload=onLoad;function getParent(a,b){return null==a?null:1==a.nodeType&&a.tagName.toLowerCase()==b.toLowerCase()?a:getParent(a.parentNode,b)}
function isClassOf(a,b){return a.className==b||0==a.className.indexOf(b+" ")||0<=a.className.indexOf(" "+b)&&a.className.indexOf(" "+b)==a.className.length-b.length-1||0<=a.className.indexOf(" "+b+" ")}function getChildByClass(a,b){if(null!=a)for(var c=0;c<a.childNodes.length;c++)if(node=a.childNodes[c],null!=node.className&&isClassOf(node,b))return node;return null}
function getDeepChildByClass(a,b,c){if(null!=a)for(var d=0;d<a.childNodes.length;d++){node=a.childNodes[d];if(null!=node.className&&isClassOf(node,b))return node;var f=getDeepChildByClass(node,b,c+1);if(null!=f)return f}return null}startList=function(){detect=navigator.userAgent.toLowerCase();msie=detect.indexOf("msie");opera=detect.indexOf("opera");navRoot=document};function doList(a){var b;for(b=0;b<a.childNodes.length;b++)node=a.childNodes[b],doList(node)}
function menuItemOver(a){if(app.isIE4||app.isIE5)a.className+=" over",document.all&&(subMenu=getChildByClass(a,"menu"),null!=subMenu&&(subMenu.overlapList=[],hideOverlaped("SELECT",subMenu)));var b=getDeepChildByClass(a,"menu");if(null!=b){a=getCoords(a);var c=yMousePos;a.top-document.documentElement.scrollTop+b.clientHeight>document.documentElement.clientHeight&&(b.clientHeight+10<=document.documentElement.clientHeight?a=document.documentElement.clientHeight+(scroll.initHeight-document.documentElement.clientHeight)-
(a.top+b.clientHeight)-25:(overSize=b.clientHeight-document.documentElement.clientHeight,mousePercent=(c-20)/(document.documentElement.clientHeight-40),a=-a.top-Math.round(mousePercent*overSize)),b.style.top=document.documentElement.scrollTop+a+"px")}}function menuItemOut(a){if(app.isIE4||app.isIE5)a.className=a.className.replace(" over",""),document.all&&(subMenu=getChildByClass(a,"menu"),null!=subMenu&&showOverlaped(subMenu))}
popup_over=function(a){li=getParent(a,"LI");null!=(menu=getChildByClass(li,"menu"))?(popupId=li,menu.className="menu1"):null!=(menu=getChildByClass(li,"menu1"))&&(popupId=li,menu.className="menu");null!=(popup=getChildByClass(li,"popup"))?(popup.className="popup1",a.src="/site/images/info.gif"):null!=(popup=getChildByClass(li,"popup1"))&&(popup.className="popup",a.src="/site/images/info.gif")};function getX(a){var b=0;do b+=a.offsetLeft,a=a.offsetParent;while(a);return b}
function getY(a){var b=0;do b+=a.offsetTop,a=a.offsetParent;while(a);return b}function hideOverlaped(a,b){var c=getX(b),d=getY(b),f=b.offsetWidth,e=b.offsetHeight,g;for(g=0;g<document.all.tags(a).length;++g){var l=document.all.tags(a)[g];if(l&&l.offsetParent){var h=getX(l),m=getY(l),p=l.offsetWidth,q=l.offsetHeight;h>c+f||h+p<c||m>d+e||m+q<d||"hidden"==l.style.visibility||(b.overlapList[b.overlapList.length]=l,l.style.visibility="hidden")}}}
function showOverlaped(a){if(a.overlapList){var b;for(b=0;b<a.overlapList.length;++b)a.overlapList[b].style.visibility=""}a.overlapList=null}var menuItems=[];
function hideOnClick(a){grandparent=a;greatgrandparent=null;i=0;for(menuItems=[];null!=grandparent;)parentLI=getParent(a,"LI"),parentLI.className=parentLI.className.replace(" over",""),par=getParent(a,"UL"),grandparent=getParent(par.parentNode,"UL"),null!=grandparent&&(greatgrandparent=getParent(grandparent.parentNode,"UL")),null==greatgrandparent&&null!=grandparent&&(par.className=par.className.replace("menu","menu1"),i++,par1=par,setTimeout("showMenu(par1)",1E3)),a=par.parentNode}
function showMenu(a){a.className=a.className.replace("menu1","menu")}function moveMenu(a){alert("Moving menu")}function switchMenu(a){a=document.getElementById(a);null!=a&&(isClass(a,"collapsed")?(switchClass(a,"collapsed",""),isClass(a,"text")?setText(a.id+"_text","-"):setImage(a.id+"_image","expanded")):(appendClass(a,"collapsed"),isClass(a,"text")?setText(a.id+"_text","+"):setImage(a.id+"_image","collapsed")))}
function switchMenuSearch(a){a=document.getElementById(a);null!=a&&(isClass(a,"collapsed")?(switchClass(a,"collapsed",""),isClass(a,"text")?setText(a.id+"_text","-"):setImage(a.id+"_image","expandedSearch")):(appendClass(a,"collapsed"),isClass(a,"text")?setText(a.id+"_text","+"):setImage(a.id+"_image","collapsedSearch")))}
function preloadImages(){if(document.images){var a="";window.location&&(a=window.location.protocol+"//www.onsemi.com");menuImages.expanded=new Image;menuImages.expanded.src=a+"/site/images/chapter_open.gif";menuImages.collapsed=new Image;menuImages.collapsed.src=a+"/site/images/chapter.gif";menuImages.expandedSearch=new Image;menuImages.expandedSearch.src=a+"/site/images/minus.gif";menuImages.collapsedSearch=new Image;menuImages.collapsedSearch.src=a+"/site/images/plus.gif"}}
function setImage(a,b){var c=document.getElementById(a);null!=c&&(c.src=menuImages[b].src)}function setText(a,b){var c=document.getElementById(a);null!=c&&(c.innerHTML=b)}function hoverRollOver(a){switchClass(a,"menuText","menuTextHover")}function hoverRollOff(a){switchClass(a,"menuTextHover","menuText")}var menuImages={};preloadImages();function Coords(a,b,c,d){this.top=a;this.left=b;this.height=c;this.width=d}
function getCoords(a){for(var b=a.offsetHeight,c=a.offsetWidth,d=a.offsetTop,f=a.offsetLeft,e=null,g=null;null!=a&&"BODY"!=a.tagName.toUpperCase();)"TBODY"!=a.tagName.toUpperCase()&&((e=a.offsetParent)&&e!=g&&(d+=e.offsetTop,f+=e.offsetLeft),g=e),a=app.isNS6?null!=e&&"BODY"==e.tagName.toUpperCase()?null:a.parentNode:!app.isIE4&&!app.isIE5||null==e||"HTML"!=e.tagName.toUpperCase()&&"BODY"!=e.tagName.toUpperCase()?a.parentElement:null;return new Coords(d,f,b,c)}
function show(a,b,c,d,f){a=document.getElementById(a);var e=null;a.style.visibility="hidden";a.style.display="block";if(null!=b&&(e=getCoords(b),app.isMac&&app.isMac&&f&&"TD"==b.tagName.toUpperCase())){if(""!=b.parentElement.parentElement.parentElement.style.left){var g=b.parentElement.parentElement.parentElement.style.left;e.left+=parseInt(g.substring(0,g.indexOf("px")))}""!=b.parentElement.parentElement.parentElement.style.top&&(b=b.parentElement.parentElement.parentElement.style.top,e.top+=parseInt(b.substring(0,
b.indexOf("px"))))}if(null!=e){a.style.top="0px";a.style.left="0px";b=getCoords(a);var l=0,g=0;if(null!=c)switch(c){case "middle":l=e.height/2;break;case "bottom":l=e.height;break;case "top":l=-b.height}if(null!=d)switch(d){case "middle":g=e.width/2;break;case "middle-left":g=-b.width/2;break;case "right":g=e.width;break;case "left":g=-b.width}c=e.top+l-b.top;f&&"right"==d&&(c-=10,c-$(window).scrollTop()+b.height>$(window).height()&&(c=b.height<=$(window).height()?$(window).height()-b.height+$(window).scrollTop()+
5:5+$(window).scrollTop()));a.style.top=c+"px";d=e.left+g-b.left;e.left+g-b.left+b.width>document.documentElement.clientWidth+document.documentElement.scrollLeft&&(d=document.documentElement.clientWidth-b.width,d+=document.documentElement.scrollLeft);d<e.left&&d+b.width>e.left+e.width&&(c<e.top&&c+b.height>e.top||c>e.top&&c<e.top+e.height)&&(d=e.left+e.width/2);$(a).css({left:d+"px",width:b.width+"px",visibility:"visible"})}}function hide(a){document.getElementById(a).style.display="none"}
function Point(a,b){this.x=a;this.y=b}function overElement(a){a=document.getElementById(a);if(null==a)return!1;getScrollXY();a=Position.get(a);return xMousePos>a.left&&xMousePos<a.left+a.width-1&&yMousePos>a.top&&yMousePos<a.top+a.height-1?!0:!1}function getScrollXY(){return new Point($(window).scrollTop(),$(window).scrollLeft)}
var Position=function(){function a(a){if(document.getElementById&&null!=document.getElementById(a))return document.getElementById(a);if(document.all&&null!=document.all[a])return document.all[a];if(document.anchors&&document.anchors.length&&0<document.anchors.length&&document.anchors[0].x)for(var b=0;b<document.anchors.length;b++)if(document.anchors[b].name==a)return document.anchors[b]}return{$VERSION:1,set:function(b,c,d){"string"==typeof b&&(b=a(b));if(null==b||!b.style)return!1;"object"==typeof c&&
(d=c,c=d.left,d=d.top);b.style.left=c+"px";b.style.top=d+"px";return!0},get:function(b){"string"==typeof b&&(b=a(b));if(null==b)return null;var c=0,d=0,f=0,e=0;var g=b.offsetParent;for(var l=b,h=b;null!=h.parentNode;){h=h.parentNode;if(null!=h.offsetParent){var m=!0;!window.opera||h!=l.parentNode&&"TR"!=h.nodeName||(m=!1);m&&(h.scrollTop&&0<h.scrollTop&&(d-=h.scrollTop),h.scrollLeft&&0<h.scrollLeft&&(c-=h.scrollLeft))}h==g&&(c+=b.offsetLeft,h.clientLeft&&"TABLE"!=h.nodeName&&(c+=h.clientLeft),d+=
b.offsetTop,h.clientTop&&"TABLE"!=h.nodeName&&(d+=h.clientTop),b=h,null==b.offsetParent&&(b.offsetLeft&&(c+=b.offsetLeft),b.offsetTop&&(d+=b.offsetTop)),g=b.offsetParent)}l.offsetWidth&&(f=l.offsetWidth);l.offsetHeight&&(e=l.offsetHeight);return{left:c,top:d,width:f,height:e}},getCenter:function(a){a=this.get(a);if(null==a)return null;a.left+=a.width/2;a.top+=a.height/2;return a}}}(),io=new Image,gcti=!1;
function readCookie(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(-1!=d.indexOf(a))return d.substring(a.length,d.length)}return null}
function ontracking(){var a=readCookie("_onTracInit");if(null!=a){location.href.split(":");var b=navigator.userAgent.toLowerCase(),c=navigator.appVersion.toLowerCase(),d="";window.screen&&(d=screen.availWidth?d+screen.availWidth:d+screen.width,d+=":",d=screen.availHeight?d+screen.availHeight:d+screen.height);d=d+":"+screen.colorDepth;io.src="/PowerSolutions/clinfo?uid="+a+"&ua="+b+"&av="+c+(""!=d?"&res="+d:"")}}ontracking();
function unfoldCurrent(){for(el=getDeepChildByClass(document.getElementById("nav_menu"),"currentContent",1);null!=el;)isClass(el,"collapsed")&&switchMenu(el.id),el=getParent(el.parentNode,"li")}
function treatAdvancedInput(a,b){var c=document.getElementById(a);if(null!=c){if("Enter Part#/Keyword/Cross-reference"==c.value||""==c.value)return c.value="Enter Part#/Keyword/Cross-reference",!1}else if(c=document.getElementById(b),null!=c&&("Enter Part#/Keyword/Cross-reference"==c.value||""==c.value))return c.value="Enter Part#/Keyword/Cross-reference",!1}
function isValidEmailAddress(a){return/[_A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[_A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/.test(a)}function stopPropagation(){window.event.cancelBubble=!0;window.event.stopPropagation&&window.event.stopPropagation()}var fdbkOpened=!1,fdbk,fdbkAjaxExpanded=!1;
function feedback(){$("#feedback").length&&(fdbk=$("#feedback"),fdbk.find(".fdbkRtg").click(function(a){stopPropagation()}),fdbk.mouseenter(function(){0==fdbkOpened&&fdbkState(1)}).mouseleave(function(){0==fdbkOpened&&fdbkState(0)}),$("#fdbkExpand,#feedback img:first-child").click(function(){fdbkOpened?closeFeedbackForm():(fdbkState(2),$("#fdbkExpand").attr("title","Click to hide feedback"))}))}function closeFeedbackForm(){fdbkState(0);$("#fdbkExpand").attr("title","Click to expand feedback")}
commands[commandIter++]="feedback()";function fdbkState(a){0==a?(a=-616,fdbkOpened&&(fdbkOpened=!1,$("#fdbkCross").hide())):1==a?a=-504:(fdbkAjaxExpanded||(fdbkAjaxExpanded=!0,$("#fdbkForm").load("/PowerSolutions/jsp/common/expandFeedback.jsp",function(){$("#fdbkTable").fadeIn();$("#fdbkForm").css("height","auto")})),a=0,fdbkOpened||(fdbkOpened=!0,$("#fdbkCross").show()));fdbk.stop().animate({right:a})}
function initPageRating(){var a=readCookie("FDBK_STARS"),b=0;null!=a&&(b=parseInt(a));a=$(".fdbkRtg").find(".rtg");starRating(a,1,b,"false","feedback");a.addClass("loaded")}var actRtg;commands[commandIter++]="initPageRating()";
function starRating(a,b,c,d,f){setStarRating(d,a,b,c);if("false"==d)actRtg=0!=b?c/b:0,a.attr("actual-rating",actRtg).append('<strong class="starRtgReport"></strong>').find(".rtgStars").css("cursor","pointer").mousemove(function(b){b=Math.ceil((b.pageX-$(this).offset().left+1)/18);5<b&&(b=5);setStars(a,b);a.attr("display-rating",b)}).mouseleave(function(){"0"==a.attr("actual-rating")?$(this).find("span").width(0):setStars(a,parseFloat(a.attr("actual-rating")))}).click(function(){saveStarRatingCallback(a,
f)});else{var e;a.find(".rtgStars").mouseenter(function(){e=a.find(".rtgInfo").html();a.find(".rtgInfo").html("For voting, <strong>open&nbsp;the&nbsp;post</strong>")}).mouseleave(function(){a.find(".rtgInfo").html(e)})}}
function starRatingBlog(a,b,c,d,f){setStarRating(d,a,b,c);if("false"==d)actRtg=0!=b?c/b:0,a.attr("actual-rating",actRtg).append('<strong class="starRtgReport"></strong>').find(".rtgBin").css("cursor","pointer").mousemove(function(b){b=Math.ceil((b.pageX-$(this).offset().left+1)/23);4<b&&(b=4);setBin(a,b);a.attr("display-rating",b)}).mouseleave(function(){$(this).find("span").width(0)}).click(function(){saveStarRatingCallback(a,f)});else{var e;a.find(".rtgBin").mouseenter(function(){e=a.find(".rtgInfo").html();
a.find(".rtgInfo").html("For voting, <strong>open&nbsp;the&nbsp;post</strong>")}).mouseleave(function(){a.find(".rtgInfo").html(e)})}}function starRtgReport(a,b){1==b?a.find(".starRtgReport").html('<strong class="succ">rating successful</strong>'):a.find(".starRtgReport").html('<strong class="fail">rating failed</strong>');a.find(".starRtgReport").css("display","none").stop(!0).fadeIn(250).delay(1200).fadeOut(1E3)}
function setStars(a,b){var c=Math.round(18*b);90<c?c=90:0>c&&(c=18);a.find(".rtgStars>span").width(c)}function setBin(a,b){var c=Math.round(23*b);92<c?c=92:0>c&&(c=23);a.find(".rtgBin>span").width(c)}function setBar(a,b){var c=Math.round(23*b);92<c?c=92:0>c&&(c=23);a.find(".rtgBar>span").width(c)}
function setStarRating(a,b,c,d){setStars(b,d/c);setBar(b,d/c);0==c?"true"==a?(a=$("#noRating").val(),b.find(".rtgStars").css("display","none"),b.find(".rtgBin").css("display","none"),b.find(".rtgBar").css("display","none")):a=$("#noVotes").val():a=1==c?"<strong>"+d+"</strong> of&nbsp;<strong>1</strong>&nbsp;"+$("#vote").val():"<strong>"+Math.round(10*d/c)/10+"</strong> of&nbsp;<strong>"+c+"</strong>&nbsp;"+$("#votes").val();b.find(".rtgInfo").html(a)}
function saveStarRatingCallback(a,b){var c="feedback"==b?document.URL:a.attr("rating-id");$.ajax({url:"/PowerSolutions/rating.do?method=saveRating&stars=true&type="+b+"&id="+encodeURIComponent(c)+"&rating="+encodeURIComponent(a.attr("display-rating")),context:document.body,success:function(c){if(""!=c){var d=c.split(";");"0"==d[0]?(c=parseInt(d[1]),d=parseInt(d[2]),setStarRating(!1,a,c,d),a.attr("votes",c).attr("votesSum",d).attr("actual-rating",d/c),"feedback"==b&&createCookie("FDBK_STARS",""+d,
60,window.location.pathname),starRtgReport(a,!0)):starRtgReport(a,!1)}else starRtgReport(a,!1)}})}function setMktCookie2Input(){var a=document.getElementsByName("marketoCookie");for(n=0;n<a.length;n++)a[n].value=getCookie("_mkto_trk")};